### ISSUE TITLE
Please document usage on windows

### ISSUE THREAD

**Issue by MatthiasSchmalz** [SAP/cloud-mta-build-tool#1020]
Since MBT uses the Linux "make" command it only runs out of the box on a Linux system.
Windows users have to at least install make or use a Linux bash.
Please mention this in your usage guide.

**Comment by young-yang03** [comment]
OK, we will update the doc soon,thanks!

@MatthiasSchmalz

**Comment by young-yang03** [comment]
@MatthiasSchmalz 

The make install on Windows and MAC are in doc : https://github.com/SAP/cloud-mta-build-tool/blob/master/docs/docs/makefile.md
