### ISSUE TITLE
Bug - MBT Build On UI5 Project Breaks Data Source URI Dependant On Path By Removing Leading /

### ISSUE THREAD

**Issue by Keith-Barrett** [SAP/cloud-mta-build-tool#1043]
There seems to be a bug in the MBT tool, which breaks UI5 builds which depend on a path based OData Source URI in the manifest.

Please provide the following info:

  - MBT Version: 1.2.23
  - OS Version: MAC & Jenkins
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Have an SAPUI5 project which contains a Data Source in the manifest using a path over a full URL as per the documenation
  A.  https://sapui5.hana.ondemand.com/sdk/#/topic/44062441f3bd4c67a4f665ae362d1109
  B. e.g 
    "dataSources": {
        "mainService": {
          "uri": "/pathToODataService/",
          "type": "OData",
          "settings": {
            "annotations": ["LocalAnnotations"],
            "localUri": "localService/metadata.xml",
            "odataVersion": "2.0"
          }
        }
2. Run mbt build on UI5 project.
3. Unzip the generated mtar so you can browse to the manifest.json file which will get deployed.
4. When examining the manifest.json in the mtar, you will see the required first / as part of the URI is removed.
  A. URI becomes "pathToODataService/" instead of "/pathToODataService/"
  B. This is breaking as this initial / is required as a UI5 feature for cetain functionality. 

Please let me know if you require any other info.

**Comment by young-yang03** [comment]
@Keith-Barrett I reproduce the problem, and it is an ui5 problem, pls contact UI5 team.

In detail, I create a testcase by BAS, mta.yaml contains a UI5 module like:
- name: project1
  type: html5
  path: project1
  build-parameters:
    build-result: dist
    builder: custom
    commands:
    - npm install
    - npm run build:cf
    supported-platforms: []

 this module's build command is :
  - npm install
  - npm run build:cf
  
  the npm run build:cf command destination is in ui5 module's package.json, in my test case it is ：
  "build:cf": "ui5 build preload --clean-dest --config ui5-deploy.yaml --include-task=generateCachebusterInfo"

after execute npm run build:cf command, manifest.json is created and the problem can be reproduced.

For MBT, it just execute the npm command in mta.yaml, and MBT will not modify manifest file internal.

**manifest file is generated by UI5 command , so pls contact UI5 team to investigate your problem.**
