### ISSUE TITLE
Env variable not getting set according to mta.yaml

### ISSUE THREAD

**Issue by Pavan-Singh-V** [SAP/cloud-mta-build-tool#1111]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

We have a CAP-Java based multi-tenant application.

We have cf-jobscheduler service with standard plan which we have defined in [mat.yaml](https://github.tools.sap/ComplaintHandling/ICHAMP/blob/release/mta.yaml#L1277)

name: cmh-job-scheduler
type: org.cloudfoundry.managed-service
parameters:
service: jobscheduler
service-plan: standard
When we use this service we have to maintain url for jobs and we set that in [mat.yaml](https://github.tools.sap/ComplaintHandling/ICHAMP/blob/release/mta.yaml#L1292) with our service [url](https://github.tools.sap/ComplaintHandling/ICHAMP/blob/release/mta.yaml#L154).

But we see this url is not getting set as expected. The configuration was working fine previously.

We see the same url is being set in User Env [variable](https://github.tools.sap/ComplaintHandling/ICHAMP/blob/release/mta.yaml#L55) the value is coming fine there.

An extra value idle is getting added in the url.

Can you please help us understand why this difference.

Please provide the following info:

  - MBT Version:  1.2.25
  - OS Version: Cloud
  - If possible, provide a link to the project.

Steps to Reproduce:

We can check in [env variables](https://canary.cockpit.btp.int.sap/cockpit#/globalaccount/ec5b091d-3ccd-4895-bab7-0cc9402c47a7/subaccount/9f28a266-f135-4193-a4a0-1c1e7ca492e2/org/22aed848-24c4-49b3-9f43-90bc50ca7ba1/space/dad6742a-f894-4ee1-b83e-b08c09c3199b/app/17813b91-fcfc-4b6a-b6b4-c5f36df87d79/environmentvariables).

[User provided Variables ](https://canary.cockpit.btp.int.sap/cockpit#/globalaccount/ec5b091d-3ccd-4895-bab7-0cc9402c47a7/subaccount/9f28a266-f135-4193-a4a0-1c1e7ca492e2/org/22aed848-24c4-49b3-9f43-90bc50ca7ba1/space/dad6742a-f894-4ee1-b83e-b08c09c3199b/app/17813b91-fcfc-4b6a-b6b4-c5f36df87d79/userdefinedvariables).

"user-provided": [ { "label": "user-provided", "name": "cmh-default-jobs", "tags": [], "instance_guid": "8b13f74d-4f81-44f9-8d77-aca50d37801e", "instance_name": "cmh-default-jobs", "binding_guid": "e0ba288c-10c0-44d1-a889-8cdcfd6b3bbf", "binding_name": null, "credentials": { "jobs": [ { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/sipstatus", "active": true, "description": "Job to get the 8D status", "httpMethod": "GET", "jobDetails": { "frequency": "15 minutes", "jobName": "notify8Dstatus", "jobType": "repeatInterval", "type": "recurring" }, "name": "Notify 8D Status", "schedules": [ { "active": true, "description": "This job runs every 15 minutes", "repeatInterval": "15 minutes", "startTime": { "date": "2021-01-01", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/shipmentconfirmationjob", "active": true, "description": "Job to auto reject and trigger shipment confirmation reminder emails", "httpMethod": "GET", "name": "Shipment Confirmation Job", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs at 00:00 every day", "startTime": { "date": "2023-02-13", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/api/meter/metering", "active": true, "description": "Used to report the metering data", "httpMethod": "GET", "name": "Report Usage", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs at 00:00 every day", "startTime": { "date": "2024-01-01", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/suppliercomplaintsautoapprove", "active": true, "description": "Job for Supplier Complaints Auto Approval", "httpMethod": "GET", "name": "Supplier Complaints Auto Approve", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs once a day", "startTime": { "date": "2023-09-01", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/scrapautocancel", "active": true, "description": "Job to auto cancel scrap Requests", "httpMethod": "GET", "name": "Scrap Request Auto Reject", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs at 00:00 every day", "startTime": { "date": "2023-08-21", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/triggerScrapReminder", "active": true, "description": "Job to trigger scrap request reminder", "httpMethod": "GET", "name": "Scrap Request Reminder", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs at 00:00 every day", "startTime": { "date": "2023-08-21", "format": "YYYY-MM-DD" } } ] }, { "action": "https://quality-canaryquality-cmh-srv-idle.cfapps.eu12.hana.ondemand.com/job/cmh/triggerSupplierApprovalReminder", "active": true, "description": "Job for Supplier Complaints Auto Approval Reminder", "httpMethod": "GET", "name": "Supplier Complaints Auto Approve Reminder", "schedules": [ { "active": true, "cron": "* * * * 0 0 0", "description": "This job runs at 00:00 every day", "startTime": { "date": "2024-02-20", "format": "YYYY-MM-DD" } } ] } ] }, "syslog_drain_url": "", "volume_mounts": [] } ],

**Comment by Pavan-Singh-V** [comment]
Hi Team,
Any Update here?

**Comment by yutaoj** [comment]
The MTA Build Tools would not change the value of the url if the yaml file has such configuration . the value 'idle' was maybe added into the url when the url  was redirect on BTP , I think you could consult why the url value is different from the BTP team.
