### ISSUE TITLE
Please publish new release with config.urls linux-amd64

### ISSUE THREAD

**Issue by navinkrishnan** [SAP/cloud-mta-build-tool#1117]
Hi Team,

We have a requirement to use devcontainers in a arm64 and run npm install.
currently, mbt dependency fails with error:
```sh
command sh -c node install cloud-mta-build-tool
npm ERR! /workspaces/devcontainers/freestyle-validate-portal/node_modules/mbt/install.js:49
npm ERR!   throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!   ^
npm ERR! 
npm ERR! Error: No binaries are available for your platform: linux-arm64
npm ERR!     at Object.<anonymous> (/workspaces/devcontainers/freestyle-validate-portal/node_modules/mbt/install.js:49:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47
npm ERR! 
npm ERR! Node.js v18.16.0
```
In the releases, I can already find [cloud-mta-build-tool_1.2.27_Linux_arm64.tar.gz](https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.2.27/cloud-mta-build-tool_1.2.27_Linux_arm64.tar.gz)
In the `mbt@1.2.27`, `install.js` in the `config.urls`, `linux-arm64` is missing.

But, I can already see in the main, it is included
https://github.com/SAP/cloud-mta-build-tool/blob/99889cfb3f4fe6fe81e0dc496801805301ddb226/install.js#L33-L34

Can you please publish this version, so we can use it ?

Versions:

  - MBT Version: 1.2.27

**Comment by yutaoj** [comment]
OK, I can reproduce this issue. and will release it .

**Comment by navinkrishnan** [comment]
Hi @yutaoj , do you have a timeline for this release ?
We have some internal workshops planned in the coming weeks, where we need this.

**Comment by TheMasonAbides** [comment]
@yutaoj Any update on when this will be released?

**Comment by zbrewer01** [comment]
@yutaoj  Do we have an update on this? Would be really nice to have this fix pushed. I've not been able to come up with a work around when using this in a container.

**Comment by yutaoj** [comment]
Hi All, this will be released soon .

**Comment by yutaoj** [comment]
Hi All, the MTA Build Tool 1.2.28 is released on npmjs.com .

**Comment by TheMasonAbides** [comment]
> Hi All, the MTA Build Tool 1.2.28 is released on npmjs.com .

Awesome..thanks @yutaoj!
