### ISSUE TITLE
devxci/mbtci-java17-node20 with node 20.11.0

### ISSUE THREAD

**Issue by heimwege** [SAP/cloud-mta-build-tool#1126]
Hey hey 👋🏻 

Currently we are using `devxci/mbtci-java17-node20` in our [CAP Java](https://cap.cloud.sap/docs/java/) app.

As UI5 tooling v4 is out which requires node >20.11.0  (see [blog post](https://community.sap.com/t5/technology-blogs-by-sap/ui5-tooling-4-0/ba-p/13769578)) I was wondering if it is planned that `devxci/mbtci-java17-node20` supports that node version.

Currently we are getting an error message because of the node version 20.9.0 being part of the latest version of `devxci/mbtci-java17-node20`:

```
10:04:46  info  mtaBuild - ==================== UNSUPPORTED NODE.JS VERSION ====================
10:04:46  info  mtaBuild - You are using an unsupported version of Node.js
10:04:46  info  mtaBuild - Detected version v20.9.0 but @ui5/cli requires ^20.11.0 || >=22.0.0
10:04:46  info  mtaBuild - 
10:04:46  info  mtaBuild - => Please upgrade to a supported version of Node.js to use this tool
10:04:46  info  mtaBuild - =====================================================================
```

**Comment by yutaoj** [comment]
Hi ,  the node version in devxci/mbtci-java17-node20 will  be upgraded in next release soon.

**Comment by yutaoj** [comment]
Hi @heimwege,  the new docker image devxci/mbtci-java17-node20 is released already.

**Comment by heimwege** [comment]
Thanks @yutaoj Pipeline is finally running ✅
