### ISSUE TITLE
Module type `nodejs` gets mapped to unexpected platform module type `javascript.nodejs`

### ISSUE THREAD

**Issue by silvestre** [SAP/cloud-mta-build-tool#1146]
Hi,

if I specify in the mta.yaml the module type `nodejs` it is highly confusing that it gets [mapped ](https://github.com/SAP/cloud-mta-build-tool/blob/739f56f01293d3a4b08cfca9a78312c707280731/configs/platform_cfg.yaml#L20-L21)to `javascript.nodejs` if I build the MTAR for the `CF` platform.

As the [Cloud Deployment Service documentation says that the `nodejs` module type is supported](https://help.sap.com/docs/btp/sap-business-technology-platform/modules) on CF it is very unexpected that it gets mapped to  `javascript.nodejs` and does not stay `nodejs` as specified, especially since the `nodejs` module implies the `buildpack` parameter, which the `javascript.nodejs` module type does not.:

![a92c1fa8-b987-4ebc-949f-e14d31b08015](https://github.com/user-attachments/assets/48e8abe3-cc74-47c5-94f7-9dac2d4d3d59)

**Comment by yutaoj** [comment]
MBT 1.2.34 has supported it
