### ISSUE TITLE
Can't specify custom mtar name during 'mbt assemble'

### ISSUE THREAD

**Issue by VaskoBozhurski** [SAP/cloud-mta-build-tool#300]
Currently the option to specify a custom output mtar name does not work for the `mbt assemble` command. No matter what custom mtar name (with or with .mtar extension) I provide the assembled mtar is always named as `<mta_id>_<mta_version>.mtar`. I want the name to be custom because the artifact name that I want to upload on the nexus differs from the MTA ID/Version combination that is the default.

Please provide the following info:

  - MBT Version: 0.2.0
  - OS Version: Windows \ Mac
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Have an MTA project ready for assemble with any mtad.yaml
2. Run `mbt assemble -m custom.mtar` or `mbt assemble --mtar custom.mtar`
3. mbt still assembles the MTAR with the default name using `<mta_id>_<mta_version>.mtar` instead of using the name supplied by the command line argument.

Logs:
```
$ ./mbt.exe assemble -m custom.mtar
[2019-03-20 14:12:48]  INFO assembling the MTA project...
[2019-03-20 14:12:48]  INFO copying the MTA content...
[2019-03-20 14:13:15]  INFO generating the metadata...
[2019-03-20 14:13:15]  INFO generating the MTA archive...
[2019-03-20 14:14:56]  INFO the MTA archive generated at: C:\work\CF\Example-Project\mta_archives\com.sap.cloud.example_1.6.0.mtar
[2019-03-20 14:14:56]  INFO cleaning temporary files...
$ ls mta_archives/
com.sap.cloud.example_1.6.0.mtar
```

**Comment by VaskoBozhurski** [comment]
Tested on a colleague's Mac and the issue is present there as well.

**Comment by ShimiT** [comment]
version 0.2.1 should address this issue.
Please check it and let me know

**Comment by VaskoBozhurski** [comment]
The custom mtar name option works now, thank you!
