### ISSUE TITLE
MBT command instead of make

### ISSUE THREAD

**Issue by IObert** [SAP/cloud-mta-build-tool#348]
Hi,

I really like this tool and I also like the integration of `make`. 
When I showed this tool to developers out there, they told me that `make` is kind of hard for them to install (especially for Windows users).
They like how easy it is to install mbt with npm.

Would it be possible to provide one `mbt` command that combines `mbt init` and `make ...`?

**Comment by ShimiT** [comment]
Hi,

Thanks for the feedback.
currently, we are working to provide command which combines both, something like `mbt build [platform]`, however, this command will still use the `makefile` to build the project.
IMO, using [chocolatey](https://chocolatey.org/packages/make) to install `make` on windows is rather simple.
If you have any doubts, please let me know.

**Comment by IObert** [comment]
Thanks for this tip! 
I personally use a Mac, but I will forward this suggestion to Windows users when I'm asked next time
