### ISSUE TITLE
Fiori Launchpad Site not being created due to error in AppRouter Deployment

### ISSUE THREAD

**Issue by I322851** [SAP/cloud-mta-build-tool#421]
Hello Colleagues,
I am trying to Build a Fiori Launchpad site on Cloud Foundry using Application Programming Model.
I have created a SAP Business Cloud Application in WEBIDE Full Stack and deploying to CF canary account. This Application contains a JAVA module to create an ODATA service endpoint, HTML5 module and a Fiori launchpad site.
There are technical errors during deployment of the Application.

Following are the steps followed and the error which is occurring during deployment:
1.	Creation of SAP Business service Application( with the option to add HTML5 repository checked during creation).
2.	Added HTML5 Module. 
-	Created a navigation in manifest.json of HTML5 App
![image](https://user-images.githubusercontent.com/37858820/59590915-aa0a1a00-910a-11e9-924c-a3429be364de.png)

3.	Added Portal services subscription to my Cloud foundry account.
4.	Added SAP Fiori Launchpad site Module to my project.
-	Changes done in the ComonDataModel.json file to added the tile created in step2.
![image](https://user-images.githubusercontent.com/37858820/59591002-d4f46e00-910a-11e9-9906-a4e0e028bda9.png)

5.	Built the Project
Tried to Deploy the project where I am having technical errors:
![image](https://user-images.githubusercontent.com/37858820/59591038-eb022e80-910a-11e9-88a2-b687a1cf0e0b.png).

following are the files having complete logs:

[MAIN_LOG.txt](https://github.com/SAP/cloud-mta-build-tool/files/3296019/MAIN_LOG.txt)
[CH_DEMO_PROJ_appRouter.txt](https://github.com/SAP/cloud-mta-build-tool/files/3296021/CH_DEMO_PROJ_appRouter.txt)

Could you please assist me in resolving the issue?

Thanks,
Chaitra

**Comment by michawai** [comment]
Hello Chaitra,

The error displayed during deployment to CF is not related to the MBT.
You should report the issue in SAP internal bug tracking tool.

Regards,
Michal
