### ISSUE TITLE
Difference from mta_archive_builder ?

### ISSUE THREAD

**Issue by lucatoldo** [SAP/cloud-mta-build-tool#451]
I do not understand how this tool relates to the mta_archive_builder, and the compatibility of the mta.yaml made for the mta_archive_builder and the one for mbt.

When I execute mbt having a mta.yaml that properly works with the mta_archive_builder I get the error message:
```
mbt build -p CF
[2019-07-12 10:47:08]  INFO generating the "Makefile_20190712104708.mta" file...
Error: generation of the "Makefile_20190712104708.mta" file failed: generation of the "Makefile_20190712104708.mta" file failed when reading the MTA file: yaml: unmarshal errors:
  line 30: field command not found in type mta.Module
```

**Comment by katunin-ng** [comment]
Hi,

The new Cloud MTA Build tool is a tool for creating MTA archives from project sources or build artifacts. Eventually, it will replace the MTA archive builder that is already in maintenance mode (only critical issues are being processed). You can find more details on the new tool here:  https://sap.github.io/cloud-mta-build-tool/

The new tool is compatible with the old one (i.e. generates equivalent MTA archives) except for the features described in this section: https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-handled-differently-in-the-cloud-mta-build-tool and temporary gaps described here: https://sap.github.io/cloud-mta-build-tool/migration/#features-that-are-temporarily-not-available-in-the-cloud-mta-build-tool.

Could you please share more details on your project, e.g. git repository or mta.yaml so we can investigate the build failure. Please also make sure you are using the latest version of the tool.

Regards
Natalia
