### ISSUE TITLE
unzip and run

### ISSUE THREAD

**Issue by lucatoldo** [SAP/cloud-mta-build-tool#452]
I have a Scala application with very large set of dependencies.
I would like to be able to build a zip file with the current directory, upload it to cf, then unzip it and then execute a specific long command that starts the service.
For example
`java -cp /blabla/1.jar:/blabla/2.jar my.class --home=/blabla`

**Comment by katunin-ng** [comment]
Hi,

"Scala" is currently not supported by the tool, i.e. it does not provide any specific builder for this module type. By default, the tool will zip the module's folder and package it into the resulting MTA archive. 

If you need to package a specific directory's zip archive as build results of your module, you can achieve it by configuring "build-parameters" for that module in mta.yaml:

-  you need to specify the name of that directory you want to zip via "build-result" parameter.
see more here: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive

- you need to set "zip" value for the "builder" parameter. see more here: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-a-builder-for-a-module

If you need different build behavior for your module, please consider using "custom" builder (https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder) or contribute a builder the Scala module type (see more on the contribution process here: https://sap.github.io/cloud-mta-build-tool/process/, we can discuss further details if you are interested).

This build tool is only responsible for packaging module's build artifacts into MTA archive.
If you have questions about the deployment of the MTA archive, please raise them here: 
https://github.com/cloudfoundry-incubator/multiapps-cli-plugin

Regards
Natalia

**Comment by lucatoldo** [comment]
Thankyou for your recommendation, that I followed accordingly.
The problem I have now is in the deployment and therefore will raise my questions at the address you provided. 
Thankyou !
