### ISSUE TITLE
BUG - "Unsupported resource type "" for platform type "CLOUD-FOUNDRY"

### ISSUE THREAD

**Issue by lucatoldo** [SAP/cloud-mta-build-tool#483]
Dear Colleagues
using  https://github.com/SAP/generator-easy-ui5 the mta.yaml that it produces builds and deploys fine. Itself is using mbt.

However,  if one has an mta.yaml such as the following

https://github.com/lucatoldo/5-simple-steps-to-wrap-a-rest-service-with-a-nice-ui5/blob/master/com.restapiexample.dummy.dummyUI/mta.yaml

Then mbt is returning the bug in the subject.

However, when using instead 
java -jar mta_archive_builder-1.1.19.jar --build=CF build
cf deploy my.mtar

then everything works fine.

Could you please check the difference and fix your tool ?
THanks

**Comment by michawai** [comment]
Hello @lucatoldo ,
This issue was fixed in our latest release [0.2.12](https://github.com/SAP/cloud-mta-build-tool/releases/tag/v0.2.12).
Regards,
Michal

**Comment by lucatoldo** [comment]
Thankyou !  I was running version 0.2.10.
I checked it now and indeed with version 0.2.12. the issue I reported is no longer happening .
Thankyou ! great work !
