### ISSUE TITLE
MBT fails on directory symlinks (win10)

### ISSUE THREAD

**Issue by drktfl** [SAP/cloud-mta-build-tool#517]
Please provide the following info:

  - MBT Version: v0.3.1
  - OS Version: win10 1809

When building an MTA project containing directory symlinks, the process aborts with error message

```
ERROR could not pack the "<module name>" module when archiving: read <symlink>: The handle is invalid.
```

The symlink is valid, though...

**Comment by allaVolkov** [comment]
Hi Dirk,

Can you please share with me you project or sample that addresses the problem.

Thank you,
Alla

**Comment by drktfl** [comment]
Hi Alla,

I have set up a small test project at https://github.com/drktfl/mbt. After cloning it, run a `mbt build` in the root folder.

Thanks for looking into this,
Dirk

**Comment by ShimiT** [comment]
HI,

The new release 0.3.4 fixes the issue please upgrade. 

Regards,
Shimon
