### ISSUE TITLE
Issue running mta build on our mta project

### ISSUE THREAD

**Issue by abhishekramesh** [SAP/cloud-mta-build-tool#526]
Hello Team,

We would like to switch from our mta archive builder to new cloud mta build tool.
We are currently building .mtar files using mta archive builder.

I followed the steps in the manual to download and install the cloud mta build tool  and GNU Make in my windows system. Then set GNU make to my PATH environment variables.

https://sap.github.io/cloud-mta-build-tool/download/

The link to our mta.yaml file https://github.wdf.sap.corp/CSI/outbound/blob/master/mta.yaml
On running the mbt build command, we get the following error.

[2019-09-20 11:05:26]  INFO generating the "Makefile_20190920110526.mta" file...
[2019-09-20 11:05:26]  INFO done
[2019-09-20 11:05:26]  INFO executing the "make -f Makefile_20190920110526.mta p=cf mtar= strict=true mode=" command...
[2019-09-20 11:05:28]  INFO validating the MTA project
[2019-09-20 11:05:28] ERROR the "mta.yaml" file is not valid:
line 60: the "outbound-service" provided property set name is already in use; a module was found with the same name on line 46
make: *** [Makefile_20190920110526.mta:30: pre_validate] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20190920110526.mta p=cf mtar= strict=true mode=" command: exit status 2

Best Regards
Abhishek

**Comment by katunin-ng** [comment]
Hi Abhishek,

Thank you for using the tool. Ans I am glad that your tool setup phase passed smoothly.

The error you get indicates that your mta.yaml is invalid. Specifically, one of your modules "provides" property set with a name of a module in line 46. It is not allowed. The names of artifacts that can be "required" in other modules or resources: modules, provided property sets, resources, must be unique within the mta.yaml. It guarantees that once this artifact is required, this configuration can unambiguously be resolved.  Unfortunately, there was a bug in the old MTA Archive builder that did not validate it properly. Please rename either module or provided property set and make sure that where the name appears in "requires" now you use the correct artifact.

Regards
Natalia
