### ISSUE TITLE
Using npm ci with the build tool

### ISSUE THREAD

**Issue by RaynDol** [SAP/cloud-mta-build-tool#530]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: 0.3.2
  - OS Version: win10
  - If possible, provide a link to the project.

Steps to Reproduce:

We are working with the new tool for a few weeks, and it's a big step forward, we notice performance improvement for our builds by 30-40% which is very surprising, this is great!
The `make` integration is great as we are able to extend with our new commands, e.g., we change the `npm install production` to `npm ci` which also give a boost to our builds, my question is if there is a way that we all benefit from it, I mean other teams will inherit our changes ?  otherwise we will use a lot of boilerplate that we want to avoid.

Thank you

**Comment by ShimiT** [comment]
Hi,

Thanks for your feedback.
One of our goal with the new MBT design was to separate the build command from the tool and be able to get from config files; hence you can use the existing configs or contribute new that everybody can leverage, please have a look at the following references 

https://github.com/SAP/cloud-mta-build-tool/blob/master/configs/builder_type_cfg.yaml#L63
https://github.com/SAP/cloud-mta-build-tool/blob/master/configs/module_type_cfg.yaml

let me know if it answers your question.

**Comment by RaynDol** [comment]
HI,

We have tested it and this is really neat as it help us to reduce our boilerplate  💯 

Thanks!

**Comment by katunin-ng** [comment]
Hi,

Thank you for sharing your feedback.
As far as I understood, this issue can be closed now.

Regards
Natalia
