### ISSUE TITLE
Path in mtad.yaml blocks discovery of package.json on CF

### ISSUE THREAD

**Issue by kommersz** [SAP/cloud-mta-build-tool#532]
- MBT Version: v0.3.2
  - OS Version: Win10
  - If possible, provide a link to the project.

I was looking for a while for why deploying a mtar file built with MBT results in an error complaining about that /home/vcap/app/package.json can not be found. It seems that MBT rewrites the "Path" parameter from the mta.yaml file in the mtad.yaml file within the mtar file, and this causes the issue. Can this be controlled/suppressed? If not, I would consider this to be a bug(?)

**Comment by allaVolkov** [comment]
Hello,
Can you, please, provide a link to the project or sample with the similar project? Or at least examples of mta and mtad yaml files and structure of mtar file?

**Comment by ShimiT** [comment]
@kommersz  - any update?

**Comment by kommersz** [comment]
I tried to reproduce now the issue, but there seems to be another issue: the build process gets stuck after calling "npm install", and then timeouts. Extending the timeout does not help either. I would like to have a look at some debug logs, but it seems like mbt is not writing any verbose logs anywhere. Is there a way to track, what is happening during the build?

**Comment by kommersz** [comment]
Yet to the issue - npm install seems to run fine, at least what is visible that it does not have any CPU use after about 40 seconds.

**Comment by ShimiT** [comment]
@kommersz - please check with version 0.3.6

**Comment by ShimiT** [comment]
@kommersz - you can try either new release `0.3.7` which reflects better the registry error.

**Comment by NinaSW** [comment]
I had the same issue (npm hangs), version 0.3.7 solve it.

**Comment by tal-sapan** [comment]
Hi @kommersz , was the issue of `npm install` process hanging resolved?
If not, could you make sure you used version 0.3.7 or newer? You can use `mbt --version` to check which version of the tool you have installed.

**Comment by tal-sapan** [comment]
Hi @kommersz,
Could you check if the issue was fixed in release 1.0.1?

**Comment by kommersz** [comment]
Issue seem to be fixed
