### ISSUE TITLE
Issue on mbt build with space in path

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/cloud-mta-build-tool#533]
Please provide the following info:

  - MBT Version: 0.3.2
  - OS Version: Win10

In my project, we use mbt and it works fine. However, for a quick check, I cloned the project again on my Desktop, where the build failed due to One Drive having spaces in the path: `C:\Users\xxx\OneDrive - xxx\Desktop\test`.

```
> mbt build -p=CF

[2019-10-22 09:47:47]  INFO generating the "Makefile_20191022094747.mta" file...
[2019-10-22 09:47:47]  INFO done
[2019-10-22 09:47:47]  INFO executing the "make -f Makefile_20191022094747.mta p=CF mtar= strict=true mode=" command...
/usr/bin/sh: C:/Users/d062651/OneDrive: Is a directory
make: *** [Makefile_20191022094747.mta:30: pre_validate] Error 126
Error: could not build the MTA project: could not execute the "make -f Makefile_20191022094747.mta p=CF mtar= strict=true mode=" command: exit status 2
```

I have a workaround, which is copying the project to another directory not managed by onedrive, but I guess this is something you'd want fixed.

I don't know whether this affects the issue, but I'm using Git Bash as Shell / Terminal Emulator. (Edit: Occurs in Powershell as well)

Thanks!

**Comment by allaVolkov** [comment]
Hi Lukas,
I didn't succeed to reproduce your problem. Can you please check that if you place your project in folder with path having spaces, build works fine. 
Thank you.

**Comment by LukasHeimann** [comment]
Hi @allaVolkov,

thanks for your response! I validated again and narrowed the issue down. So in our project, we install the mbt via node devDependencies and run it via npm scripts, so the local mbt is used automatically. When using the npm script, the issue arises. When calling the mbt directly, everything works fine.

You can validate this by installing the mbt through npm (`npm i --save-dev mbt`) and then using the npm executor to run (`npx mbt build`). Alternatively, you can add the script to the package.json:
```json
  "scripts": {
    "build-mta": "mbt build"
  },
```
and run via `npm run build-mta`.

Thank you very much!
Lukas

**Comment by LukasHeimann** [comment]
Making it a two-step process works just fine:

`npx mbt init` and `mbt init` generate an identical `Makefile.mta`, both `npx make -f Makefile.mta p=cf` and `make -f Makefile.mta p=cf` work just fine. So it must be something in the way mbt calls make during mbt build, I suspect.

**Comment by allaVolkov** [comment]
Hi Lukas,
Your edge case works just fine in my tests. Both working with npm mbt build and with package json succeed. Maybe you can provide some another hint for reproducing the problem / example. Does the problem raise when your project reside in regular folder (not OneDrive)?

**Comment by LukasHeimann** [comment]
Yes, I tried it outside of One Drive (C:\Users\xxx\dev\test\folder with space\).
I'll try to check if I can produce a minimal example, maybe something within the project setup is interfering here.
Is there a way to get more debug messages out of this? Line 30 referenced in the error message is the call to mbt validate, but maybe a special module and builder is affected...

**Comment by tal-sapan** [comment]
Hi,

The issue was fixed, and the fix will be available in the next release.

Best regards,
Tal
