### ISSUE TITLE
Cannot add node_modules on mac os

### ISSUE THREAD

**Issue by olirogers** [SAP/cloud-mta-build-tool#542]
Unable to generate a mtar using MTB if the module contains a node_modules directory. If the directory is removed, the command works.

Please provide the following info:
  - MBT Version: 0.3.4
  - OS Version: mac os 10.14.6
  - If possible, provide a link to the project. https://github.com/olirogers/mbt-test

Steps to Reproduce:
1. Clone the project https://github.com/olirogers/mbt-test
2. Run npm install to create node_modules directories. From the root dir:
`npm install`
`cd srv && npm install`

3. Run mbt from the root dir: `mbt build`

Output is:

```
>> mbt build
[2019-11-02 19:35:32]  INFO generating the "Makefile_20191102193532.mta" file...
[2019-11-02 19:35:32]  INFO done
[2019-11-02 19:35:32]  INFO executing the "make -f Makefile_20191102193532.mta p=cf mtar= strict=true mode=" command...
[2019-11-02 19:35:32]  INFO validating the MTA project
[2019-11-02 19:35:32]  INFO validating the MTA project
[2019-11-02 19:35:32]  INFO building the "mbt-srv" module...
[2019-11-02 19:35:32]  INFO the build results of the "mbt-srv" module will be packed and saved in the "/Users/<user>/git/mbt-test/.mbt-test_mta_build_tmp/mbt-srv" folder
[2019-11-02 19:35:32] ERROR could not pack the "mbt-srv" module when archiving: stat ../mime/cli.js: no such file or directory
make: *** [mbt-srv] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20191102193532.mta p=cf mtar= strict=true mode=" command: exit status 2
```

This is the same result as using the npm builder.

If you delete the `srv/node_modules` folder, or exclude the folder, all is successful!

Any ideas?

**Comment by ShimiT** [comment]
HI,

I did all the steps on my MAC OS Mojave 10.14.6 and the build was successful and produce a deployable mtar file,  see the following logs:

```
 ! ? ~/P/mbt-test ? ? ? cd srv                                                                                                                                                                                                                   Sun Nov  3 09:26:53 2019
 ~/P/mbt-test ? ? ? srv ? npm install                                                                                                                                                                                                            
added 50 packages from 37 contributors and audited 126 packages in 0.755s
found 0 vulnerabilities
+ npm@6.12.1
 ~/P/mbt-test ? ? ? srv ? cd ..                                                                                                                                                                                                           7.1s ? Sun Nov  3 09:27:24 2019
 ~/P/mbt-test ? ? ? mbt build                                                                                                                                                                                                                    Sun Nov  3 09:28:00 2019
[2019-11-03 09:28:04]  INFO generating the "Makefile_20191103092804.mta" file...
[2019-11-03 09:28:04]  INFO done
[2019-11-03 09:28:04]  INFO executing the "make -f Makefile_20191103092804.mta p=cf mtar= strict=true mode=" command...
[2019-11-03 09:28:04]  INFO validating the MTA project
[2019-11-03 09:28:04]  INFO validating the MTA project
[2019-11-03 09:28:04]  INFO building the "mbt-srv" module...
[2019-11-03 09:28:04]  INFO the build results of the "mbt-srv" module will be packed and saved in the "/Users/i056926/Projects/mbt-test/.mbt-test_mta_build_tmp/mbt-srv" folder
[2019-11-03 09:28:04]  INFO generating the metadata...
[2019-11-03 09:28:04]  INFO generating the MTA archive...
[2019-11-03 09:28:04]  INFO the MTA archive generated at: /Users/i056926/Projects/mbt-test/mta_archives/mbttest_0.0.1.mtar
[2019-11-03 09:28:04]  INFO cleaning temporary files...

```


However, from your error, it's clear that the packing process looking for `../mime/cli.js` file, and I don't see it in your code as you are using a simple `express` web application server. 
Do you know who is require this file? 

Regards,
Shimon

**Comment by olirogers** [comment]
hi,

Thanks for testing. I'm not sure why mine doesn't work then! I'm on node 10.16.0 if that is different?

From the package-lock.json, mime is required by send which is required by serve-static which is required by express itself.

Oli

**Comment by ShimiT** [comment]
Hi,

Did you try to `re-clone` the project? using nvm I switch to your version 10.16.0 and it works for me

Best Regards,
Shimon

**Comment by simfer** [comment]
Hi, I'm on macOS Catalina 10.15.1 and I'm having exactly the same issue.
I'm following this blog: <https://blogs.sap.com/2019/10/24/test-your-cap-nodejs-applications-with-authentication-locally/> which is using the application here <https://github.com/jowavp/SAP-CAPM-Nodejs-Authorisation-example>. Well, even with this application I'm receiving the same kind of error:
![err01](https://user-images.githubusercontent.com/6877529/68110743-d83b9b00-feed-11e9-88af-dee91cf85416.png)

What can we do?
Simmaco

**Comment by tal-sapan** [comment]
I couldn't reproduce it either (on Windows).
@olirogers @simfer What is the mbt version you use to run the build? (You can find the version with `mbt --version`)
Could you check if it's the latest version?

**Comment by simfer** [comment]
This is mine:

i045523@C02Z30W7LVDR Temp % mbt --version
MBT version v0.3.4

I just installed it.
Simmaco

**Comment by IObert** [comment]
I have the same issue and I found a workaround for the meantime: downgrading to v0.3.2 fixes the issue

**Comment by ShimiT** [comment]
@IObert  @olirogers @simfer  - we have just released a new version (0.3.5) with a fix for relative symbolic links, please check it and let me know.

**Comment by IObert** [comment]
Was the release successful? NPMJS says that 0.3.4 is still the most recent version?

**Comment by ShimiT** [comment]
@IObert  - it is just released, please try again.

**Comment by IObert** [comment]
Awesome! I see it now and this version works well, thanks a lot.

**Comment by olirogers** [comment]
Thanks @ShimiT. I've just put in 0.3.5 and I don't get the issue anymore!

Thanks for the quick response!

**Comment by simfer** [comment]
Thanks it works now!
Simmaco

**Comment by vijayvikramsap1987** [comment]
I am having issue with mbt build

![image](https://user-images.githubusercontent.com/60575713/117540677-dfd18800-b02d-11eb-807e-e82d2faa19bf.png)

**Comment by katunin-ng** [comment]
@vijayvikramsap1987 
Hi! 
MBT requires GNU make installed in the build environment. Please follow the guidelines here: https://sap.github.io/cloud-mta-build-tool/makefile/
Regards
Natalia
