### ISSUE TITLE
Not able to resolve variable from xs-security.json

### ISSUE THREAD

**Issue by i320676** [SAP/cloud-mta-build-tool#547]
- MBT Version: 0.3.2

Steps to Reproduce:

**file:  mta.yaml**

resources:
  - name: test-uaa
    type: com.sap.xs.uaa
    parameters:
      **default-xsappname: test-ax-xsapp**
      path: ./xs-security.json
      service: xsuaa
      service-plan: broker

**File: xs-security.json**
{
	**"xsappname": "${default-xsappname},**
	"tenant-mode": "dedicated",
	"scopes": [{	  

when build default-xsappname does not resolve and throw below error, if we give xsappname directly it will work

Service operation failed: Controller operation failed: 502 Updating service "test-uaa" failed: Bad Gateway: Error creating service "test-uaa" from offering "xsuaa" and plan "broker": Service broker error: Service broker xsuaa failed with: Error creating application null (Error parsing xs-security.json data: Inconsistent xs-security.json: Invalid xsappname "$default-xsappname": May only include characters 'a'-'z', 'A'-'Z', '0'-'9', '_', '-', '\', and '/'.)

**Comment by tal-sapan** [comment]
Hi,

The reason you get the error message from the deploy service is that it doesn't support using [placeholders](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/490c8f71e2b74bc0a59302cada66117c.html) (like `${default-xsappname}`) in JSON files.

The MTA Build Tool packages the JSON file inside the mtar during the build without any changes. If you would like to use placeholders, you can embed the content of the xs-security.json file (at least the parameters that have placeholders) into your mta.yaml according to [this documentation](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/a36df26b36484129b482ae20c3eb8004.html).

Best regards,
Tal

**Comment by i320676** [comment]
@tal-sapan IN older build tool it was supported and it was working fine, so its not supported in latest (cloud-mta-build-tool) ?

**Comment by tal-sapan** [comment]
Hi,

The old version of the MTA Build Tool embedded all the content of the JSON file inside the mtad.yaml instead of packing the file in the mtar. In the new tool the file content isn't embedded.

Best regards,
Tal

**Comment by oyasnev** [comment]
Hi Tal,

have found this issue item because our team is experiencing the same problem during migration to the MBT. Would you see a possibility to add a note regarding the new approach into the Migration page (https://sap.github.io/cloud-mta-build-tool/migration/) - I think it could save lots of time for other teams with their migrations too :-)

Thank you!

Best regards,
Oleg

**Comment by katunin-ng** [comment]
Hi Oleg,
This is indeed a good idea. We will add this point to the documentation. 
Thank you
Natalia
