### ISSUE TITLE
Console output truncated upon termination

### ISSUE THREAD

**Issue by kommersz** [SAP/cloud-mta-build-tool#591]
- MBT Version: 1.0.0
  - OS Version: Ubuntu 18.04.3 LTS on Windows Subsystem for Linux
 
This is a general comment - in this environment, MBT seems to truncate console output upon exiting during build. The console output (potentially from the launced processes) is obviously truncated at some point, and MBT finishes the output with "Error: could not build the MTA Project...".
If would be great if the console output could be flushed or awaited before terminating the process, because the most important messages about the reason of e.g. build failure get lost, since they are usually trailing the console output.

**Comment by tal-sapan** [comment]
Could you attach an example of such a build with all of the output from the build? I'm not sure I understand what output is terminated and in which case.

**Comment by kommersz** [comment]
Here is a short one (the issue for a failed build here was an invalid mta.yaml file, but the problem I want to demonstrate is the truncated log):

`
[2019-11-18 14:32: 30]   INFO generating the "Makefile_20191118143230.mta" file... 
[2019-11-18 14:32: 30]   INFO done
[2019-11-18 14:32: 30]   INFO executing the "make -f Makefile 2019111814323Ø.mta p=cf mtar= strict=true mode=" command... 
[2019-11-18 14:32: 30]   INFO validating the MTA project 
[2019-11-18 14:32: 30] ERROR the "mta.yaml" file is not valid: 
line 36: the "business-coError: could not build the MTA project: could not execute the "make -f Makefile_20191118143230.mta p=cf mtar strict=true mode=" command : exit status 2 
`

Look at "coError:". this should have been a console output like (what has never been written on the console is in square brackets: [] ):
line 36: the "business-co[**nfiguration-srv" project ...**]

Since the output is truncated, I may not figure out, what issues caused the build failure.

**Comment by tal-sapan** [comment]
@kommersz Thanks for the response. What exactly did you change in the mta.yaml to get an error? Is the error about an undefined required property set?
I'm trying to reproduce it but so far I'm unsuccessful...

**Comment by kommersz** [comment]
It is absolutely not dependent on the error in the mta.yaml file. Many different errors yield the same issue. I suppose there are processes (e.g. make) launched by mbt, that do somehow not finish writing their output buffer to the console before mbt writes something like "_Error: could not build the MTA project:_", and closes the output.

**Comment by tal-sapan** [comment]
What is the version of `make` you have installed (you can find it with `make --version`)?

**Comment by tal-sapan** [comment]
> What is the version of `make` you have installed (you can find it with `make --version`)?

Please ignore this question, I managed to reproduce the issue

**Comment by tal-sapan** [comment]
Hi @kommersz,
Could you check if the issue was fixed in release 1.0.1?

**Comment by kommersz** [comment]
Issue seem to be fixed.
