### ISSUE TITLE
Conflict between project name and "provides" name

### ISSUE THREAD

**Issue by kommersz** [SAP/cloud-mta-build-tool#592]
- MBT Version: 1.0.0

Hi,

There is a mta.yaml file containing the following part:

  _(line 35) - name: project-ui-deployer
    type: com.sap.html5.application-content
    path: ui/project-ui-deployer/
    parameters:
      memory: 512M
      disk-quota: 512M
      buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git#v1.6.49
    requires:
      - name: project-ui-host
    build-parameters:
      requires:
        - name: project-ui
          artifacts:
            - './*'
          target-path: resources/project-ui
    provides:
(line 51)      - name: project-ui-deployer
        public: true_

mbt complains that the project name and the provides are the same:
**line 51: the "project-ui-deployer" provided property set name is already in use; a module was found with the same name on line 35**

In my view it should be legitimate to have the two names the same - one is the name of a project, the other is the name of the built artifact, as I understand.

**Comment by katunin-ng** [comment]
Hi, 

The names of the provided properties sets, resources and modules must be unique within the mta.yaml.
This ensures that when you refer a name in the 'requires' section it can be unambiguously resolved. 
Please rename one of the conflicting artifacts and make sure that in 'requires' section, if you have such, you use the correct object's name.
 
Regards
Natalia
