### ISSUE TITLE
Adjust Dockerfile Node Version to be Compatible with Hana Client

### ISSUE THREAD

**Issue by bmcdonn2** [SAP/cloud-mta-build-tool#602]
This issue applies to the following:

  - Docker Image Version: 1.0.0 (available on dockerhub here: [devxci/mbtci](https://hub.docker.com/r/devxci/mbtci))

This docker image uses Node version v12.13.0 which is incompatible with commonly used hana-client packages. This issue is documented in #368 

https://github.com/SAP/cloud-mta-build-tool/blob/7eb92592417ed9ff2a471db2ab6d322e971662c1/Dockerfile#L7

I was able to confirm this error by trying to run `npm install` for a project that uses a hana dependency (in my case `@sap/hdi-deploy@3.8.2` which has a dependency on `@sap/hana-client@2.3.123`) for both the standard docker images of `node:10.13.10` and `node:12.13.10` (while also making sure to install other dependencies like `node-gyp`). What I found was that the install suceeded in the `10.13.10` version and failed in the `12.13.10` version, which is identical to the findings in issue #368.

Given that projects built with this tool will often require interaction with hana, I feel like a compatible version of node should be used in the image.

**Comment by ShimiT** [comment]
HI,

As we want to keep our tools up to date we have provided the [lastest stable node].(https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.0)
In general, we want to avoid downgrading components to old versions.
Please forward the issue to `@sap/hana-client@2.3.123`.

Meanwhile, I've updated our minor release `0.5.0` with  `node:10.17.0`, see https://hub.docker.com/layers/devxci/mbtci/0.5.0/images/sha256-ec59807852b10eabf3929fd14056a992003fa1d41c89559912f4d8a675018029` use it until the hana-client issue will be solved.

**Comment by bmcdonn2** [comment]
I appreciate you including the old version in the minor release. I'll try to report the issue with the hana-client dependencies but it's a bit more difficult for me as a non-SAPer given those repositories aren't on GitHub 😉

**Comment by ShimiT** [comment]
np, i'll try to forward it to the right team :)
