### ISSUE TITLE
Docker: grunt not in path

### ISSUE THREAD

**Issue by CCFenner** [SAP/cloud-mta-build-tool#605]
When building a project containing a module using the `@sap/grunt-sapui5-bestpractice-build` plugin and the *grunt builder*, `grunt` is not found during the build.

```sh
ERROR could not build the "my-ui" module: could not execute the "grunt" command: exec: "grunt": executable file not found in $PATH
```

However,`grunt` is installed in `<module>/node_modules/.bin/` and with the *old* build tool it was suficiend to build with `PATH=./node_modules/.bin:$PATH`.
So it looks like previously the build was executed in the module path where `./node_modules/.bin` points to the correct directory which is not the case any longer.

Please provide the following info:
  - MBT Version: 1.0.0
  - OS Version: provided in container
  - If possible, provide a link to the project. (contact me)

Steps to Reproduce:

1. start `devxci/mbtci`
2. run `export PATH=./node_modules/.bin:$PATH mbt build --platform cf`

One solution could be to install NPM's `grunt-cli` to detect the nearest `grunt` executable.

**Comment by ShimiT** [comment]
Please use `devxci/mbtci:1.0.1` which includes `grunt-cli:1.3.2` .
let me know if it works for you.

**Comment by CCFenner** [comment]
That solved the issue, thanks!
