### ISSUE TITLE
docs(usage): correct target help text

### ISSUE THREAD

**Issue by CCFenner** [SAP/cloud-mta-build-tool#617]
The provided help text seems to be wrong:

```
  -t, --target string        The path to the results folder; the current path is set as the default
```

Actually the default folder is `./mta_archives`

In the [docs](https://github.com/SAP/cloud-mta-build-tool/blob/2213802236fb4c4433dfeb44b61cbf979a8749b3/docs/docs/usage.md) it's saying this which is more accurate:

> The folder for the generated MTAR file. If this parameter is not provided, the MTAR file is saved in the mta_archives subfolder of the current folder. If the parameter is provided, the MTAR file is saved in the root of the folder provided by the argument.

Please provide the following info:
  - Used Container: `devxci/mbtci:1.0.4`
  - MBT Version: as provided in Docker
  - OS Version: as provided in Docker

Steps to Reproduce:

1. run `mbt build --help`

**Comment by allaVolkov** [comment]
Help text fixed in version 1.0.8
