### ISSUE TITLE
"property is not provided" error is returned in mbt build for property defined in the extension file

### ISSUE THREAD

**Issue by stefanhennrich** [SAP/cloud-mta-build-tool#625]
Hello, 
Please provide the following info:

  - MBT Version: 1.0.4
  - OS Version: Linux 
  - If possible, provide a link to the project.: https://github.wdf.sap.corp/IPD/ipd.cf.central

Steps to Reproduce:

1. installing mbt
2. cloning Project repo https://github.wdf.sap.corp/IPD/ipd.cf.central
3. executing : mbt build -p=cf -e=mtad-aws-canary-ipd-dev-provider-ipd.mtaext

There is still a complaint about the missing url settings, which are part of the extension files. I am wondering, since it looks that the extension file has not been taken into account.
 
Would you kindly provide advice how to perform the mbt build/which settings needs to be done by the DEV team?
 
Output from my shell (also xmake and Pipeline had issues, so first wanted to get it work locally):

<code>
C02Y41XNJGH5:ipd.cf.central d049457$ mbt build -p=cf -e=mtad-aws-canary-ipd-dev-provider-ipd.mtaext
[2019-12-03 12:50:38]  INFO Cloud MTA Build Tool version 1.0.4
[2019-12-03 12:50:38]  INFO generating the "Makefile_20191203125038.mta" file...
[2019-12-03 12:50:38]  INFO done
[2019-12-03 12:50:38]  INFO executing the "make -f Makefile_20191203125038.mta p=cf mtar= strict=true mode=" command...
[2019-12-03 12:50:38]  INFO validating the MTA project
[2019-12-03 12:50:38] ERROR the "mta.yaml" file is not valid: 
line 56: the "url" property of the "ipd-app-router" module is unresolved; the "ipd-xray/url" property is not provided
line 61: the "url" property of the "ipd-app-router" module is unresolved; the "ipd-xray-data/url" property is not provided
make: *** [pre_validate] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20191203125038.mta p=cf mtar= strict=true mode=" command: exit status 2
</code>

BR
Stefan

**Comment by littleamigo** [comment]
Hi Stefan,
It works for me without the equals sign. You may try it:
`mbt build -p=cf -e mtad-aws-canary-ipd-dev-provider-ipd.mtaext`
BR
Henrik

**Comment by katunin-ng** [comment]
Hi Stefan,
You reference a property from the mta.yaml, but this property is not declared in this descriptor.
You should at least define it in mta.yaml. The value can be empty in mta.yaml and provided in mta ext.

Regards
Natalia

**Comment by zyh425285360** [comment]
Hi Natalia
In fact, the property is set into mta.yaml https://github.wdf.sap.corp/IPD/ipd.cf.central/blob/master/mta.yaml

 - name: ipd-xray
    group: destinations
    properties:
      name: ipd-xray
      url: "~{url}"
  - name: ipd-xray-data
    group: destinations
    properties:
      name: ipd-xray-data
      url: "~{url}"

And also defined url in extension file https://github.wdf.sap.corp/IPD/ipd.cf.central/blob/master/mtad-aws-canary-ipd-dev-provider-ipd.mtaext
resources:
- name: ipd-xray
  properties:
    url: 'https://xraycontrolstebofwk.int.sap.hana.ondemand.com/xRayControls/resources/sap/dfa/help'
- name: ipd-xray-data
  properties:
    url: 'https://cp1canary.int.sap.hana.ondemand.com/dps'

Regards,
Michelle
© 2019 GitHub, Inc.

**Comment by katunin-ng** [comment]
Hi Michelle,

The links in mta.yaml that you refer to is where you want to consume the ipd-xray (line 52)  or ipd-xray-data(line 57)  resources and properties that you expect them to provide: ~{url} (line51/56 correpondingly). These setting appear under ‘requires’ section of the ipd-app-route module.

In mta.yaml, you declare the ipd-xray and ipd-xray-data resources on lines 191 and 192 correpondingly:

- name: ipd-xray
- name: ipd-xray-data

The property that you refer to in lines 51/56 is not declared there.
Therefore, ~{url} is not resolved. 
To fix it, you should add the property in the mta.yaml at least without a value: 

resources:
- name: ipd-xray
  properties:
     url: 
- name: ipd-xray-data
  properties:
     url: 

Regards
Natalia

**Comment by zyh425285360** [comment]
Hi Natalia,

Thanks for suggestion, it could work fine now.

Best Regards,
Michelle
