### ISSUE TITLE
Unable to run build, '@sap/hdi-deploy@3.10.0' is not in the npm registry.

### ISSUE THREAD

**Issue by i025126** [SAP/cloud-mta-build-tool#634]
Please provide the following info:

  - MBT Version: 1.0.4
  - OS Version: Windows 10
  - If possible, provide a link to the project.
https://git.build.ingka.ikea.com/bw-mixed-models/ROOT.git

1.  Clone GIT to local repository 
2.  Open command prompt in github\root 
3. run: mbt build -p=xsa
C:\Users\i025126\OneDrive - SAP SE\Documents\GitHub\ROOT>mbt -v
Cloud MTA Build Tool version 1.0.4
C:\Users\i025126\OneDrive - SAP SE\Documents\GitHub\ROOT>mbt build
[2019-12-13 15:21:52]  INFO Cloud MTA Build Tool version 1.0.4
[2019-12-13 15:21:52]  INFO generating the "Makefile_20191213152152.mta" file...
[2019-12-13 15:21:52]  INFO done
[2019-12-13 15:21:52]  INFO executing the "make -f Makefile_20191213152152.mta p=cf mtar= strict=true mode=" command...
[2019-12-13 15:21:52]  INFO validating the MTA project
[2019-12-13 15:21:52]  INFO validating the MTA project
[2019-12-13 15:21:52]  INFO building the "db" module...
[2019-12-13 15:21:52]  INFO executing the "npm install --production" command...
....npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sap%2fhdi-deploy - Not found
npm ERR! 404
npm ERR! 404  '@sap/hdi-deploy@3.10.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'db'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i025126\AppData\Roaming\npm-cache\_logs\2019-12-13T14_21_57_496Z-debug.log
[2019-12-13 15:21:57] ERROR could not build the "db" module: could not execute the "npm install --production" command: exit status 1
make: *** [Makefile_20191213152152.mta:37: db] Error 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20191213152152.mta p=cf mtar= strict=true mode=" command: exit status 2

Attempt to install @sap/hdi-deploy have been done using
npm config set registry https://npm.sap.com/
C:\Users\i025126\OneDrive - SAP SE\Documents\GitHub\ROOT>npm install @sap/hdi-deploy
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.sap.com/debug
npm ERR! 404
npm ERR! 404  'debug@3.1.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i025126\AppData\Roaming\npm-cache\_logs\2019-12-13T14_25_20_483Z-debug.log
---- the log shows:
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @sap/hdi-deploy@3.11.6 checking installable status
17 http fetch GET 200 https://npm.sap.com/@sap%2fhana-client 75ms
18 silly pacote version manifest for @sap/hana-client@2.4.162 fetched in 78ms
19 http fetch GET 404 https://npm.sap.com/debug 56ms
---- and I get the fail
It seems that It tries to find either "@sap/hdi-deploy" or "debug" and depending the npm registry used one is always missing.

What is the trick

Best
Søren

**Comment by tal-sapan** [comment]
Hi,

Please add a `.npmrc` file to your nodejs modules with this line:
`@sap:registry=https://npm.sap.com`
This makes sure that for packages under `@sap` the `npm.sap.com` registry is used.

Best regards,
Tal

**Comment by i025126** [comment]
Hi Tal

Thank you for pointing me in the right direction. Using the command "npm config ls -l" I found where the npm was looking for the .npmrc file and could update it with the line. The build now works.
