### ISSUE TITLE
Make fails with no error message

### ISSUE THREAD

**Issue by daniel-kurzynski** [SAP/cloud-mta-build-tool#635]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version:
  - OS Version:
  - If possible, provide a link to the project.

Steps to Reproduce:

1. 1.0.5
2. Win10
3.

```
mbt build
[2019-12-18 14:57:01]  INFO Cloud MTA Build Tool version 1.0.5
[2019-12-18 14:57:01]  INFO generating the "Makefile_20191218145701.mta" file...
[2019-12-18 14:57:01]  INFO done
[2019-12-18 14:57:01]  INFO executing the "make -f Makefile_20191218145701.mta p=cf mtar= strict=true mode=" command...
Error: could not build the MTA project: could not execute the "make -f Makefile_20191218145701.mta p=cf mtar= strict=true mode=" command: exit status 3221225781
```

There is no information what the issue could be. Make is meanwhile on the path.

**Comment by tal-sapan** [comment]
Hi,

Instead of `mbt build` could you run these commands:
`mbt init`
`make -f Makefile.mta p=cf`
And attach the output?
(Note: this creates a file called `Makefile.mta` which you can delete at the end)
Also, could you attach the `mta.yaml`?

**Comment by katunin-ng** [comment]
@daniel-kurzynski could you please try the steps above and share the output and the mta.yaml file?
Thank you
Natalia

**Comment by allaVolkov** [comment]
@daniel-kurzynski  as no information has been provided I'm closing the issue.
If the problem still exists please reopen and provide the requested data.

Regards,
Alla

**Comment by daniel-kurzynski** [comment]
Issue was solved be reinstalling make.
