### ISSUE TITLE
could not build the MTA project: could not execute the makefile

### ISSUE THREAD

**Issue by I319505** [SAP/cloud-mta-build-tool#637]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: Cloud MTA Build Tool version 1.0.4
  - OS Version: MAC 10.15.2
  - If possible, provide a link to the project.

Steps to Reproduce:

1. I set up abt tool in my Mac
2. I copied the mta.yaml from mtad.yaml from assembly-cf folder to parent folder.
3. When I run the following command to build end up with error as follows

C02V64XYHTD6:baseline I319505$ mbt build -p cf
[2019-12-13 14:43:34]  INFO Cloud MTA Build Tool version 1.0.4
[2019-12-13 14:43:34]  INFO generating the "Makefile_20191213144334.mta" file...
[2019-12-13 14:43:34]  INFO done
[2019-12-13 14:43:34]  INFO executing the "make -f Makefile_20191213144334.mta p=cf mtar= strict=true mode=" command...
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: could not build the MTA project: could not execute the "make -f Makefile_20191213144334.mta p=cf mtar= strict=true mode=" command: exit status 1

**Comment by tal-sapan** [comment]
Hi,

This seems to be a problem with your environment:
`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`
Could you try to fix this issue (e.g. search in stackoverflow) and re-try the build? It seems an update of xcode command-line tools might be needed.

**Comment by katunin-ng** [comment]
@I319505 any updates?

**Comment by tal-sapan** [comment]
Hi @I319505,

We have added this issue to the [troubleshooting section](https://sap.github.io/cloud-mta-build-tool/troubleshooting/#make-cannot-run-on-mac-os) of the documentation. Please follow the instructions there and check if it solves your issue.

Best regards,
Tal

**Comment by allaVolkov** [comment]
@I319505 I'm closing the issue.
If there is still some problem with this, please reopen.
