### ISSUE TITLE
Could not build the MTA project

### ISSUE THREAD

**Issue by ssimsekler** [SAP/cloud-mta-build-tool#641]
BUG

  - MBT Version: 1.0.5
  - OS Version: Windows 10 Enterprise
  - If possible, provide a link to the project: https://github.com/SAP-samples/cloud-foundry-cap-azure-cities/
- Make version: GNU Make 3.81 (Windows)

Steps to Reproduce:

1. Clone the repository from the aforementioned GitHub url
2. Install Node modules
3. Execute npm run build:mta

The execution fails complaining:

> ''C:' is not recognized as an internal or external command,
> operable program or batch file.
> make: *** [pre_validate] Error 1
> Error: could not build the MTA project: could not execute the "make -f Makefile_20191223164421.mta p=cf mtar= strict=true mode=" command: exit status 2

Command output attached.
[build.log](https://github.com/SAP/cloud-mta-build-tool/files/3995628/build.log)

Kind Regards

Serdar

**Comment by tal-sapan** [comment]
Hi,

Could you try to clone and build the project inside a folder that doesn't contain a space character and let me know if it works?

**Comment by ssimsekler** [comment]
Hi @tal-sapan 

Thnaks for your response. The initial problem is resolved after moving the folder to a path with no spaces but the build still fails for some other reason:

> [2019-12-24 10:05:55]  INFO Cloud MTA Build Tool version 1.0.5
> [2019-12-24 10:05:55]  INFO generating the "Makefile_20191224100555.mta" file...
> [2019-12-24 10:05:55]  INFO done
> [2019-12-24 10:05:55]  INFO executing the "make -f Makefile_20191224100555.mta p=cf mtar= strict=true mode=" command...
> [2019-12-24 10:05:56]  INFO validating the MTA project
> [2019-12-24 10:05:57]  INFO validating the MTA project
> [2019-12-24 10:05:57]  INFO building the "city-cap-router" module...
> [2019-12-24 10:05:57]  INFO executing the "npm install --production" command...
> ..npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
> .
> > @sap/node-jwt@1.6.5 install C:\SAP\dev\cloud-foundry-cap-azure-cities\app\node_modules\@sap\node-jwt
> > node ./build.js
> 
> ...Build failed
> .npm WARN city-cap-router@1.0.0 No repository field.
> npm WARN city-cap-router@1.0.0 No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @sap/node-jwt@1.6.5 install: `node ./build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @sap/node-jwt@1.6.5 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\simsekls\AppData\Roaming\npm-cache\_logs\2019-12-24T10_06_04_877Z-debug.log
> [2019-12-24 10:06:04] ERROR could not build the "city-cap-router" module: could not execute the "npm install --production" command: exit status 1
> make: *** [city-cap-router] Error 1
> Error: could not build the MTA project: could not execute the "make -f Makefile_20191224100555.mta p=cf mtar= strict=true mode=" command: exit status 2
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! city-explorer-demo-app@1.3.6 build:mta: `cds build/all && cds deploy && mbt build -p=cf`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the city-explorer-demo-app@1.3.6 build:mta script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\simsekls\AppData\Roaming\npm-cache\_logs\2019-12-24T10_06_05_058Z-debug.log

**Comment by tal-sapan** [comment]
Hi,
Could you add the versions of node (`node -v`) and npm (`npm -v`)?
And if you have a git bash, could you try to run the build there instead of in windows command prompt?

**Comment by tal-sapan** [comment]
As for the issue with the space in the project path, could you upgrade your `make` to version 4.2.1 as described [here](https://sap.github.io/cloud-mta-build-tool/makefile/) and try again?

**Comment by ssimsekler** [comment]
Hi @tal-sapan 

Node version: 12.9.0
NPM version: 6.13.1

I got the same result when I tried with Git Bash.

Attaching the log file:
[2019-12-24T14_00_56_631Z-debug.log](https://github.com/SAP/cloud-mta-build-tool/files/3998465/2019-12-24T14_00_56_631Z-debug.log)

For the "space in the project path" problem, I downloaded make-windows from the Git rep and copied it as make.exe in the existing GnuWin32 folder which is in the PATH.

I didn't get the initial error, i.e. ''C; could not be found...; I get the same recent error:

> [2019-12-24 14:17:16] ERROR could not build the "city-cap-router" module: could not execute the "npm install --production" command: exit status 1

**Comment by tal-sapan** [comment]
Could you try to run `npm install --production` inside the `app` directory and check if you get this error?

**Comment by ssimsekler** [comment]
Hi @tal-sapan 

I am afraid this returns the same error. Log is attached:
[2019-12-27T10_54_25_162Z-debug.log](https://github.com/SAP/cloud-mta-build-tool/files/4005102/2019-12-27T10_54_25_162Z-debug.log)

**Comment by tal-sapan** [comment]
Hi @ssimsekler,

In this case this is probably an issue with the `@sap/node-jwt` node package and not the MBT.
You could try to use node version 10.x instead of 12.x and check if this solves the issue (if you would like to keep your node 12.x installation you can use a `nvm` to switch between node versions). If not please open an issue on that node package instead.

Best regards,
Tal

**Comment by katunin-ng** [comment]
Hi,

I am closing the issue as not related to the tool itself.

Regards
Natalia
