### ISSUE TITLE
.DS_Store file got packed into mtar

### ISSUE THREAD

**Issue by AndrewWUw** [SAP/cloud-mta-build-tool#652]
When build using the tool, it appears the .DS_Store file will also be packed into the final mtar file. Then when deploying the created mtar to SCP CF, the deployment failed with error

**Error: Adding "cfg/.DS_Store" for deploy... failed [8211700] (STDOUT, APP/TASK/deploy)#**

Please provide the following info:

  - MBT Version: 1.0.7
  - OS Version: Mac OS Mojava 10.14.6

Steps to reproduce:

1. Run mbt build to build mtar
2. Run cf deploy created.mtar

More logs for the deploy:
#2.0#2020 01 07 05:39:35.559#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]    [2020-01-07 05:39:32.275169000] Error: Adding "cfg/.DS_Store" for deploy... failed [8211700] (STDOUT, APP/TASK/deploy)#

#2.0#2020 01 07 05:39:35.559#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]      at "cfg/.hdiconfig" (0:0) (STDOUT, APP/TASK/deploy)#

#2.0#2020 01 07 05:39:35.560#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]    [2020-01-07 05:39:32.275144000] Error: "cfg/.hdiconfig": Configuration does not define a build plugin for file suffix "ds_store" [8210015] (STDOUT, APP/TASK/deploy)#

#2.0#2020 01 07 05:39:35.560#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]      at "cfg/.DS_Store" (0:0) (STDOUT, APP/TASK/deploy)#

#2.0#2020 01 07 05:39:35.560#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]    [2020-01-07 05:39:32.275124000] Error: "cfg/.DS_Store": could not create a compile unit for the file [8211714] (STDOUT, APP/TASK/deploy)#

#2.0#2020 01 07 05:39:35.560#Z#DEBUG#com.sap.cloud.lm.sl.xs2.db.executeTaskTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-6###
[PollExecuteTaskStatusExecution] [Tue Jan 07 05:39:32 UTC 2020]    [2020-01-07 05:39:32.260891000] Adding "cfg/.DS_Store" for deploy... (STDOUT, APP/TASK/deploy)#

**Comment by katunin-ng** [comment]
Hi,

The MBT automatically packages all content of a build result folder, which is the module's root folder by default or the folder configured by the corresponding build parameter. You can exclude files/folders by using the 'ignore' option https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive.
Regards
Natalia

**Comment by AndrewWUw** [comment]
> automatically

Hi Natalia

Thank you for getting back to me. As you pointed out, I tried to put ignore to all of the modules in my app, then tried to rebuild. But the build result still not excluding .DS_Store files. I tried to use '.DS_Store', 'DS_Store', '*.DS_Store' in the ignore expression, and none of them seem to work. Also, is it possible to set it as global build parameter instead?

    build-parameters:
      ignore: ['*.DS_Store']

**Comment by katunin-ng** [comment]
Hi,

I see. We will investigate the issue.

"ignore" option is not considered at the global level: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-a-global-build
The reason is that the "ignore" parameter configures what to exclude from a module build results when they are packaged into an MTA archive. The global build results are not packaged directly, only if it produces output that is configured to be a module build result.

Regards
Natalia

**Comment by tal-sapan** [comment]
Hi,

Which folder in your project is the file packaged from? And where inside the mtar is it created?

Best regards,
Tal

**Comment by allaVolkov** [comment]
Hi Andrew,
 Please try to use something like: ["cfg/.DS_STORE"] , 
which is: <relative (to the module) path to ignored file>/.DS_STORE

Regards,
Alla

**Comment by allaVolkov** [comment]
Hi Andrew, 
I'm closing the issue. If you still have a problem please reopen.
Regards,
Alla
