### ISSUE TITLE
Deployment failing after moving to new MBT

### ISSUE THREAD

**Issue by mv93** [SAP/cloud-mta-build-tool#653]
Link to application: https://github.wdf.sap.corp/S4HANA-Procurement-GB/GB

Steps to Reproduce:
After the movement the compilation went through but the deployment is failing.
Error: _2019-12-24T04:17:05.671+0000 [STG/0] ERR SEVERE: Unhandled exception in Buildpack main method: None of the available runtimes: [Tomee, Tomee7, Tomcat, Java Main] support the application in the specified path. Failed to compile droplet: Failed to compile droplet: exit status 9_

Please help us resolve this issue

**Comment by katunin-ng** [comment]
Hi,

Could you please elaborate on the environment where you build and deploy the project.
Are you doing it from Web IDE (please provide the link), CLI, pipeline?
What is the target platform: XSA or CF?

Regards
Natalia

**Comment by allaVolkov** [comment]
Hello mv93, 

You are not properly reference build results in mta.yaml.  web*.jar that has to be archived is created in folder web/target. So it has to be:
  build-parameters:
      build-result: 'web/target/web*.jar'

 Please change, try and let us know if it solves the problem.

Regards,
Alla

**Comment by mv93** [comment]
this worked for me. thanks!
