### ISSUE TITLE
Using an MTA extension takes over extension Id as artifact ID

### ISSUE THREAD

**Issue by MatthiasSchmalz** [SAP/cloud-mta-build-tool#672]
We have switched to using the new MTA builder in our XMake build.
We specify an additional MTA extension for the MTA build. It looks the Id of the extension overrules the Id which is used as Maven artifact Id for pushing it to Nexus. Thus the Nexus link for downloading the file changes unexpectedly.

The following is the .xmake config:
[buildplugin]
name=mta
**mbt-v2=true
mta-version=latest
mta-group-artifact=com.sap.mta:mta_archive_builder**
mtar-group=com.sap.uics
mtar-build-target=CF
maven-version=3.3.3
maven-group-artifact=org.apache.maven:apache-maven
**mta-extension=mtaExtensions/xmake.release.mtaext.yaml**
java-version=1.8.0_172-sap-01
node-version=10.15.3
no-proxy=true

Inside the mta.yaml we have ID: fdc-cf-service
The extension file contains
extends: fdc-cf-service
ID: fdc-cf-service.xmake

When staging the xmake build the expected url would be
http://nexus.wdf.sap.corp:8081/stage/repository/28b650c48095-releases-20200121-072454593-331/com/sap/uics/fdc-cf-service/1.19.13-B-20200121072323+080e261d174e2232ab4dd8d4312bddb6b6bec325/fdc-cf-service-1.19.13-B-20200121072323+080e261d174e2232ab4dd8d4312bddb6b6bec325.mtar
But instead it produced 
http://nexus.wdf.sap.corp:8081/stage/repository/28b650c48095-releases-20200121-072454593-331/com/sap/uics/fdc-cf-service.xmake/1.19.13-B-20200121072323%2B080e261d174e2232ab4dd8d4312bddb6b6bec325/fdc-cf-service.xmake-1.19.13-B-20200121072323%2B080e261d174e2232ab4dd8d4312bddb6b6bec325.pom

With the old build tool this did not happen.

You can find the Git source here: https://github.wdf.sap.corp/UI-related-Cloud-Services/fdc-cf

**Comment by michawai** [comment]
Hi,
As this error happens in internal SAP xMake, please open an internal bug so it can be farther be processed.
Regards,
Michal

**Comment by MatthiasSchmalz** [comment]
Created https://sapjira.wdf.sap.corp/browse/DEVXBUGS-5857
