### ISSUE TITLE
Add a option to skip the "install" step

### ISSUE THREAD

**Issue by IObert** [SAP/cloud-mta-build-tool#673]
Many of the developers I speak to "complain" that the MTA archive for nodesjs-based projects become really large. A simple CAP project for example already comes >90MB. 

This happens due to the large size of the `node_modules` folder. I guess it should be possible to create the archive without the `node_modules` folder. This would have the benefit of saving time during the build and upload step. It would also come with the price that the modules will have to be downloaded during the deployment (e.g. this step will take longer).

I think it would make sense to leave this decision (whether to include the `node_modules` to the archive) up to the developers and offer them an opt-out parameter.

**Comment by katunin-ng** [comment]
Hi,

Are you familiar with the 'ignore' build parameter: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive?
I think it's what you are looking for.

Regards
Natalia

**Comment by IObert** [comment]
This is exactly what I've been looking for :) 
Many thanks!
