### ISSUE TITLE
Build fails with new build tool using webide

### ISSUE THREAD

**Issue by mv93** [SAP/cloud-mta-build-tool#687]
Steps to Reproduce:

1. clone : https://github.wdf.sap.corp/S4HANA-Procurement-GB/GB
2. build 
3. Error: could not build the MTA project: could not execute the "make -f Makefile_20200205043050.mta p=cf mtar= strict=true mode=" command: exit status 2
10:12:17 AM (MTA BUILD) The "Task for mta build" process finished with code 1

![image](https://user-images.githubusercontent.com/6816172/73811966-13a57880-4801-11ea-8c3a-05d9eb3520d7.png)

**Comment by michawai** [comment]
Hi @mv93 ,
As this is an internal SAP project it should be reported in internal SAP bug tracking system.
Regards,
Michal

**Comment by allaVolkov** [comment]
Hi @mv93 ,

In GBUI module you use incorrectly .npmrc. Registry that is declared there does not include both app router and eslint dependency. You have to find registry that includes both or redefine .npmrc in another way. When we exclude eslint dependency and remove .npmrc build works. You can test it.
![GB-issue](https://user-images.githubusercontent.com/42611923/74675797-07d09380-51bd-11ea-9bf7-439a265d7c73.png)
![GB-issue](https://user-images.githubusercontent.com/42611923/74675831-1e76ea80-51bd-11ea-8753-2005cc816d9f.png)

Regards, 
Alla
