### ISSUE TITLE
Is there a command to exclude unit tests when triggering the mbt build of a mta project.

### ISSUE THREAD

**Issue by abhishekramesh** [SAP/cloud-mta-build-tool#689]

**Comment by katunin-ng** [comment]
HI,

There is no dedicated command to exclude the unit tests. But you can instruct the tool not to package the results of unit tests in the mta archive using 'ignore' build parameter: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive.
If you do not want to run unit tests in certain cases, you can use 'custom' builder with explicit commands and include/exclude unit tests run via mta extension.  See more on custom builder here: 
https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder

Regards
Natalia

**Comment by abhishekramesh** [comment]
Thanks Natalia , it was very helpful.
