### ISSUE TITLE
Module artifact path in MTAR includes in subfolder = build-result folder, not flatten like before

### ISSUE THREAD

**Issue by acwwat** [SAP/cloud-mta-build-tool#690]
Please provide the following info:

  - MBT Version: 1.0.9
  - OS Version: Windows 10 64-bit
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Create an MTA application that contains a Node.js module built using Grunt to create build results in a non-root folder (e.g. `dist`). For instance, I have a use case to use `@sap/grunt-sapui5-bestpractice-build` to minify, generate `*-preload.js`, etc. for SAPUI5. Then specify the `build-result` build parameter to this folder, so the artifact zip file will have the content of this folder. For example:

```
 - name: testweb
   type: html5
   path: testweb
   build-parameters:
      builder: grunt
      build-result: dist
```

2. Run `mbt build` to build the module.
3. Open the mtar file in the `mta_archives` folder and observe that the data.zip will be located in `<module-name>/dist` instead of just `<module-name>`. This is unlike the old MTA Archive Builder JAR which we are currently using in our CI pipeline.

I tried to look at the code and it seems that the `GetModuleTargetArtifactPath()` function in `build_params.go` has the logic that sets the `artifactRelPath` based on the `moduleSourceArtifactPath`.

**Comment by katunin-ng** [comment]
HI,

Yes. This new MBT behavior is by design. The build results are stored in the mtar under the folder specified in the buil-results. The path in the MANIFEST.MF file is set accordingly. 
If you for some reason access the artifacts of the packaged mtar, please adjust your code in CI accordingly.

Regards
Natalia
