### ISSUE TITLE
Documentation , Beginners Guide for MTA and Build Tool

### ISSUE THREAD

**Issue by Thilaknath** [SAP/cloud-mta-build-tool#692]
Hello Team,

I would like to know if there is any at all good documentation available for MTA deployments and the usage of Cloud MTA build tool for the same.

It is extremely tough to find decent documentation if we want to share it with a new joiner who would want to contribute to the project.

**Comment by katunin-ng** [comment]
Hi,

If you are looking for the basic information about MTA, please check this guide: https://www.sap.com/documents/2016/06/e2f618e4-757c-0010-82c7-eda71af511fa.html

Here you can find documentation for the Cloud MTA build usage and configuration: https://sap.github.io/cloud-mta-build-tool/

And here you can find some examples on specific use cases of MTA usage: https://github.com/SAP-samples/cf-mta-examples

Let us know if you have specific questions or issues so we can assist or refer you to the relevant colleagues.

Regards
Natalia
