### ISSUE TITLE
Option to skip tests during build

### ISSUE THREAD

**Issue by risapisa** [SAP/cloud-mta-build-tool#693]
It would be nice if we could optionally skip running tests in maven during the mbt build. Currently in our project we have more than 80 tests and as a result a normal build takes more than 6 minutes.

**Comment by michawai** [comment]
Hi @risapisa,
You can configure a custom builder which will run mvn with skipTests option.
See Cloud MBT user guide in [Configuring the custom builder](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder).
Regards,
Michal

**Comment by risapisa** [comment]
Ok, I understand! Thank you for your quick response :)
