### ISSUE TITLE
Cloud MTA Build Tool gets stuck during "Neo" Build

### ISSUE THREAD

**Issue by mhealey2018** [SAP/cloud-mta-build-tool#696]
We have been using "Cloud MTA Build Tool" as part of Jenkins Pipeline to build HTML5 applications for  deployment to "Neo" and  "Cloud Foundry"

In the past week we have suddenly experienced difficulties with "Cloud MTA Build Tool" building an HTML5 using UI5 builder for deployment to Neo (Multi-Target Archive Builder works)

mta.yaml + UI5.yml + package.json added at end

The build tool gets stuck on the step highlighted below, and does not continue:

Command in Jenkins job:

_# execute MTA build
mbt build -p=neo_

14:56:04 [2020-02-21 14:56:04]  INFO Cloud MTA Build Tool version 1.0.9
14:56:04 [2020-02-21 14:56:04]  INFO generating the "Makefile_20200221145604.mta" file...
14:56:04 [2020-02-21 14:56:04]  INFO done
14:56:04 [2020-02-21 14:56:04]  INFO executing the "make -f Makefile_20200221145604.mta p=neo mtar= strict=true mode=" command...
14:56:04 [2020-02-21 14:56:04]  INFO validating the MTA project
14:56:04 [2020-02-21 14:56:04]  INFO validating the MTA project
14:56:04 [2020-02-21 14:56:04]  INFO building the "devopsui5gbmhe3" module...
14:56:04 [2020-02-21 14:56:04]  INFO executing the "npm install --production" command...
14:56:26 ......................npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
14:57:13 ..............................................npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
14:57:27 ..............
14:57:27 > core-js@2.6.9 postinstall /var/lib/jenkins/workspace/DevOpsProject/Mike.Healey/neoexample/devops-devopsui5gbmhe3mta-push-build-free/src/node_modules/@ui5/cli/node_modules/core-js
14:57:27 > node scripts/postinstall || echo "ignore"
14:57:27 
14:57:27 [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
14:57:27 
14:57:27 [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
14:57:27 [96m>[94m https://opencollective.com/core-js [0m
14:57:27 [96m>[94m https://www.patreon.com/zloirock [0m
14:57:27 
14:57:27 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
14:57:27 
14:57:28 .npm notice created a lockfile as package-lock.json. You should commit this file.
14:57:28 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/@ui5/cli/node_modules/fsevents):
14:57:28 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
14:57:28 
14:57:28 added 691 packages from 718 contributors and audited 5207 packages in 78.745s
14:57:28 found 16 vulnerabilities (6 low, 10 moderate)
14:57:28   run `npm audit fix` to fix them, or `npm audit` for details
**14:57:28 [2020-02-21 14:57:28]  INFO the build results of the "devopsui5gbmhe3" module will be packed and saved in the "/var/lib/jenkins/workspace/DevOpsProject/Mike.Healey/neoexample/devops-devopsui5gbmhe3mta-push-build-free/src/.src_mta_build_tmp/devopsui5gbmhe3" folder**

**MTA.YAML**

_schema-version: '2.1'
parameters:
  hcp-deployer-version: 1.1.0
ID: ui5gbmhe3mta
version: 1.0.0
modules:
  - name: devopsui5gbmhe3
    type: com.sap.hcp.html5
    path: .
    parameters:
      version: '${timestamp}'
    build-parameters:
      builder: npm

**UI5.yaml**

specVersion: '1.0'
metadata:
  name: devopsui5gbmhe3
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  customTasks:
    - name: webide-extension-task-updateNeoApp
      afterTask: generateVersionInfo
      configuration:
        destDir: dist
        appFolder: webapp
        nameSpace: test
    - name: webide-extension-task-updateManifestJson
      afterTask: webide-extension-task-updateNeoApp
      configuration:
        appFolder: webapp
        destDir: dist
    - name: webide-extension-task-lint
      afterTask: webide-extension-task-updateManifestJson
      configuration:
        destDir: dist
        appFolder: webapp
        nameSpace: test 
    - name: webide-extension-task-resources
      afterTask: webide-extension-task-lint
      configuration:
        nameSpace: test

**package.json**

{
  "name": "devopsui5gbmhe3",
  "version": "0.0.1",
  "description": "",
  "private": true,
  "devDependencies": {
    "@ui5/cli": "1.7.0",
    "@sap/ui5-builder-webide-extension": "1.0.9"
  },
  "scripts": {
    "build": "ui5 build --a",
    "test": "uiveri5",
    "linting": "eslint ."
  },
  "ui5": {
    "dependencies": [
      "@sap/ui5-builder-webide-extension"
    ]
  }
}

**Comment by michawai** [comment]
Hi,
Please try to build the project locally to see if it is reproducible. 
If the build is successful when running locally then it might be related to the environment you're running on.
Regards,
Michal

**Comment by usersam01** [comment]
Hello,
I have the same issue. The build runs successfully locally.
However the problem seems to be with docker image the build usually runs on : devxci/mbtci
I tried several versions of it but it always fails right after downloading the node modules.
Regards,
Hossem

**Comment by mhealey2018** [comment]
Hello Michal

The issue is not experienced when running locally (on WIndows 10 desktop with v1.0.10) for either "grunt" or "UI5 Builder" .

With "Cloud MTA Builder" under the control of Jenkins, I can confirm that the "grunt" builds are successful too, it's only the "UI5 Builder" builds that get stuck at the following step (but Multi Target Application Archive Builder builds both successfully)

12:27:47 [2020-02-26 12:27:47]  INFO the build results of the "devopsui5gbmhe3" module will be packaged and saved in the "/var/lib/jenkins/workspace/DevOpsProject/Mike.Healey/neoexample/devops-devopsui5gbmhe3mta-push-build-free/src/.src_mta_build_tmp/devopsui5gbmhe3" folder

Jenkins is currently configured to ensure the following npm extensions are deployed globally:

/NodeJS/bin/npm install -g grunt-cli grunt grunt-ui5 @ui5/cli @ui5/builder node-gyp mbt hdb

Many thanks

Mike

**Comment by usersam01** [comment]
Hello mhealey2018,

I'm facing the same problem even with CF targets.
However I managed to get the build working when I changed -t option in the mta build command that Jenkins runs and chose a different target for the mtar than the current directory("./" that points to the Jenkins workspace)

**Comment by srinikitha09** [comment]
Hello, could you try by adding a "name" parameter under parameters object. Simply as shown below and test:

parameters:
   name: "testapp"

Thanks and Regards,
Nikitha

**Comment by mhealey2018** [comment]
Nikitha that is standard practise for mta.yaml anyway. The legacy build tool works fine.

Also, the simplicity of the mbt build -p=neo command is that:
1) archive is store in folder /mta_archives/ - we are happy with the default target
2) mtar name is generated from ID + version in mta.yaml

I can see where the issue is at least. My test application is the simplest you can have i.e. UI5 application with a single view.

Yet the size of the data.zip generated during the build is ridiculously large (code is checked out to dir /src). The file just gets larger and larger ! It's now up to 16 GB since the screenshot !!!

![Capture](https://user-images.githubusercontent.com/43146125/75363903-b5752e00-58b2-11ea-8dc3-9b13fa028a52.JPG)

**Comment by srinikitha09** [comment]
Hi @mhealey2018 , but in your Mta.yaml config, I couldn’t see any such parameter defined. To my knowledge, for neo deployement, cloud mta build tool, requires this name parameter which should be inside parameters object. Could you please try with that parameter and let me know if you still have the issue.

**Comment by mhealey2018** [comment]
Dear Nikitha

The issue remains - I have tried various combinations of the mta.yaml reverting from Scheme 2.1 to 3.1 and back again - with name, without name.

Here is the latest mta.yaml variant with "hanging" still being experienced:

ID: devopsui5gbmhe3mta
version: 1.0.0
_schema-version: '3.1'
parameters:
  description: devopsui5gbmhe3mta
  hcp-deployer-version: 1.1.0
modules:
- name: devopsui5gbmhe3
  type: com.sap.hcp.html5
  path: .
  build-parameters:
    builder: npm
  parameters:
    name: devopsui5gbmhe3
    version: 1.0.0

Many thanks

Mike

**Comment by srinikitha09** [comment]
Hello Mike,
yes, I understood the problem. I tried to reporduce the same error, when running the build locally on my windows machine, but I can confirm that the problem is not with the `mtaBuild ` step from piper but rather with the tool itself (using v1.0.7).

Thanks and Regards,
Nikitha

**Comment by usersam01** [comment]
Hello,

I launched the mbt build tool with different versions locally on my workspace right after a git clone operation ==> the build went fine
I tried the mbt build on the Jenkins workspace created for mtaBuild step from the piper project ==> the build fails and the data.zip file keeps getting bigger (as in an infinite loop).
Anyway, since the mbtBuild step from the piper project closed this issue as it seemed related to this one, can we get some kind of confirmation from the mbt team ?

**Comment by mhealey2018** [comment]
Do I need to raise this as a SAP incident in OSS, or is the correct channel to report issues with the "Cloud MTA Build Tool" please?

**Comment by ShimiT** [comment]
@mhealey2018  - Could you try building your project using our docker image and check the folder size?  https://hub.docker.com/r/devxci/mbtci

**Comment by mhealey2018** [comment]
ShimiT I am not using a docker container. This is a simple build on a virtual machine.

NodeJS 12.6.1 is installed as a global too on Jenkins with following installed globally:

mbt grunt-cli grunt grunt-ui5 node-gyp hdb @ui5/cli

Script in Jenkins freestyle project runs **mbt build -p=neo**

Defaults MTAR name i.e. <mtarname>_<mtarversion>.mtar is fine as is the default target /mta_archives/

The fact that grunt works ok indicates that this is isolated to "UI5 builder" builds for neo.

Thanks

Mike

**Comment by ShimiT** [comment]
@mhealey2018 - With docker, we can isolate the issue as the binary run in stateless mode.  in order to proceed please provide a link or permission to your project.

**Comment by mhealey2018** [comment]
> @mhealey2018 - With docker, we can isolate the issue as the binary run in stateless mode. in order to proceed please provide a link or permission to your project.

Hello @ShimiT 

I have added you as a contributor to the reference that I have now uploaded to GitHub.

Thanks in advance

Mike

**Comment by mhealey2018** [comment]
The SAP Standard help for [Apply CI/CD to SAP Fiori Development on SAP Cloud Platform](https://help.sap.com/viewer/3324745951b44b578bd65221d2ff8f9a/Cloud/en-US/1fd3a82e80b34a8a807c880850d64e11.html) advises mta.yaml for UI5 build should be:

![image](https://user-images.githubusercontent.com/43146125/75999100-ab2de200-5ef9-11ea-9766-093f2240c317.png)

I have just received advice that a build for neo deployment should not have path set to . instead set to webapp (i.e. where html5 code is) - so what is correct?

I have reverted my mta,yaml to following. The MTAR generates now, however the application shows a blank screen at runtime - though the same application deploys successfully when built with "Multi Target Application Archive Builder 1.1.20":

For a simple UI5 application i.e. of construct - what is the correct configuration of mta.yaml to achieve a successful mtar deployment to Neo?:

ID: devopsui5gbmhe3mta
version: 1.1.2
_schema-version: '3.1'
parameters:
  hcp-deployer-version: 1.1.0
modules:
- name: devopsui5gbmhe3
  type: html5
  path: webapp
  build-parameters:
    builder: npm
  parameters:
    name: devopsui5gbmhe3
    version: 1.0.1

![image](https://user-images.githubusercontent.com/43146125/76003296-c865af00-5eff-11ea-9f8a-a9903f06ec30.png)

**Comment by mhealey2018** [comment]
@ShimiT  advised the following for the mta.yaml:

_The path: . is not supported, in the way you can reclusively upload your project with an infinite loop especially on CI environment .change it and reference to the module, like webapp_

but this contradicts SAP's own advice [CI/CD to SAP Fiori Development on SAP Cloud Platform](https://help.sap.com/viewer/3324745951b44b578bd65221d2ff8f9a/Cloud/en-US/1fd3a82e80b34a8a807c880850d64e11.html)

![image](https://user-images.githubusercontent.com/43146125/76008108-04504280-5f07-11ea-8472-c9be45fcfe16.png)

Although an MTAR is now generated following the adjustment and deploys to Neo subtenant, the application does not run and results in a white screen:

Just to remind you that the MTAR that was generated locally via Cloud MTA Build tool did deploy successfully to Neo. This implies that there is an issue when running same tool under Jenkin's control.

**Comment by ShimiT** [comment]
Currently, the root path for a module reference is not supported on CI based env; We will discuss the ways to handle it internally and update accordingly.

**Comment by mhealey2018** [comment]
> Currently, the root path for a module reference is not supported on CI based env; We will discuss the ways to handle it internally and update accordingly.

Thanks ShimiT. 

Given that the legacy MTA builder tool is due for decommissioning and Web IDE Full-Stack defaults to UI5 builder + Cloud MTA Build Tool, this will definitely require a solution for Neo.

**Comment by katunin-ng** [comment]
@mhealey2018 just to make sure we understand the problem: you manage to build the project successfully with the old MBT both locally and in your Jenkins build on a virtual machine (not docker). The build is also successful (meaning you can generate and deploy your MTA archive and the application runs as expected) when you run the new Cloud MTA Build tool locally. The problem is only reproducible when you try to build the project with the new tool in your Jenkins-based pipeline. Please confirm/correct.

Please also check the version of the MBT tools (old and new) that you are using and let us know.

I would also appreciate if you test the problematic flow after adding additional build-parameter to your mta.yaml "build-result : dist" as follows: 

![image](https://user-images.githubusercontent.com/16318153/76159790-8e2d2500-612c-11ea-9794-823970216812.png)

Thank you
Natalia

**Comment by mhealey2018** [comment]
Dear @katunin-ng 

I am pleased to confirm that adding the "build-result: dist" to mta.yaml has resolved our issue.

Thanks to your extended team for the advice and great to see tha the Cloud MTA Build Tool is working as designed too.

I will close this issue straightaway.

Mike

**Comment by katunin-ng** [comment]
@mhealey2018 Thank you for the update and your kind feedback.
