### ISSUE TITLE
The build parameter "ignore" has no effect

### ISSUE THREAD

**Issue by vraguna** [SAP/cloud-mta-build-tool#697]
Dear Colleagues,

We are using cloud mta build tool to build the application and deploy to Cloud foundry through pipeline. I followed the document (https://sap.github.io/cloud-mta-build-tool/configuration/) and used the build parameter "ignore" in mta.yaml to exclude files (E.g. localService/mockserver.js, extended_runnable_file.html,...). I don't see any effect since i am still able to access those file using the URL.

Those files can be accessed using the URL by the user, which we want to avoid for security reason.
https://...sap.cfapps.eu10.hana.ondemand.com/comsapsamviewer/localService/mockserver.js

Project:
https://github.wdf.sap.corp/CSI/Sam/blob/CSI110_DevOps_excludeFiles_SecIssue/mta.yaml

Pipeline:
https://csi.codepipes.wdf.sap.corp/job/CSI/job/SalesAuditManager_PullRequest-Sam-xMake~Build-Build/520/

Please help us to fix this.

Regards,
Vinod Kumar Ragunathan

**Comment by katunin-ng** [comment]
Hi Vinod Kumar Ragunathan,

The "ignore" build parameter is applied to the build results before they are packaged into the mta archive. In your case, the build results are located in the 'dist' folder, therefore pathes that you specify should be relative to this folder. I think you should change the configuration as follows:

ignore: ["localService/", "test/", "extended_runnable_file.html", "fioriHtmlRunner.html"] .

We will update the tool documentation to make this point clear. Thank you for the feedback.

Regards
Natalia

**Comment by vraguna** [comment]
Hi Natalia,

Thanks for your above comments. We tried the above "ignore" configuration but it doesn't seems to work, we still able to access the files using the above given URL.

I request you, if possible to have a short meeting to discuss this issue. Please let me know your feasible time so i will set up a meeting. Thanks.

Regards,
Vinod Kumar Ragunathan

**Comment by katunin-ng** [comment]
@vraguna sure. Please send me an MR.
Regards
Natalia

**Comment by vraguna** [comment]
Thanks Natalia. I have sent an MR.
Regards,
Vinod
