### ISSUE TITLE
Pipeline MTA cloud tool version causing API to fail

### ISSUE THREAD

**Issue by abhishekramesh** [SAP/cloud-mta-build-tool#702]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 
We are using mta-version 'latest' in our .xmake config file in pipeline.

Please provide the following info:

  - MBT Version:Cloud MTA Build Tool version 1.0.10
  - OS Version:
  - If possible, provide a link to the project.
https://github.wdf.sap.corp/CSI/outbound/blob/master/.xmake.cfg

Steps to Reproduce:
We were initially have the same issue during manual deployment. The MTA cloud tool was not packaging the servicecds.xml file properly and after deployment the API were failing.
We were able to resolve this by locally installing the latest version of MTA cloud tool 1.0.10. 
We now know the latest version of MTA cloud tool is building MTAR properly and fixing our API, but the pipeline is not using the same and on deployment the API fails again.

We have already set mta-version to latest in our pipeline xmake config.
https://github.wdf.sap.corp/CSI/outbound/blob/master/.xmake.cfg

Can you please check how we can consume the latest mta cloud tool version for our pipeline , so we can fix the issue?

**Comment by michawai** [comment]
Hi,
You are trying to build your project from internal SAP xMake build system.
Please open a bug in the relevant xMake plugin.
Regards,
Michal
