### ISSUE TITLE
Error in building MTAR xmake ERROR: mbt returned 1

### ISSUE THREAD

**Issue by Showkath** [SAP/cloud-mta-build-tool#703]
Do you want to request a report a bug /consultation ?

Also posted issue on XMAKE but no response as of now 
https://github.wdf.sap.corp/dtxmake/xmake-mta-plugin/issues/54

Hi ,

Our Git hub Repository : https://github.wdf.sap.corp/visit-managment-system/vmsN

We are following below article to use new Cloud MTA Build Tool
https://jam4.sapjam.com/articles/IkCqw7bqLOECQXkFhdRwah

XMAKE : https://github.wdf.sap.corp/visit-managment-system/vmsNg/blob/master/.xmake.cfg

Project build is success using mbt build -t ./ command but to using xmake

we followed your instructions
https://github.wdf.sap.corp/dtxmake/xmake-mta-plugin/blob/master/README.md
https://github.wdf.sap.corp/visit-managment-system/vmsNg

Detailed Logs can be found here

https://prod-build10000.wdf.sap.corp/job/visit-managment-system/job/visit-managment-system-vmsng-master-CI-linuxx86_64/3/console

Error

18:10:00 ERROR - argv "/xmake/xtr/MS/com.sap.prd.distributions.org.nodejs.linuxx86_64/nodejs/0.12.0/node-v0.12.0-linux-x64/bin/node" "/xmake/xtr/MS/com.sap.prd.distributions.org.nodejs.linuxx86_64/nodejs/0.12.0/node-v0.12.0-linux-x64/bin/npm" "install"
18:10:00 ERROR - node v0.12.0
18:10:00 ERROR - npm v2.5.1
18:10:00 ERROR - code ECONNREFUSED
18:10:00 ERROR - errno ECONNREFUSED
18:10:00 ERROR - syscall connect
18:10:00 INFO -
18:10:00 ERROR - Error: connect ECONNREFUSED
18:10:00 ERROR - at exports.errnoException (util.js:746:11)
18:10:00 ERROR - at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
18:10:00 ERROR - { [Error: connect ECONNREFUSED]
18:10:00 ERROR - code: 'ECONNREFUSED',
18:10:00 ERROR - errno: 'ECONNREFUSED',
18:10:00 ERROR - syscall: 'connect',
18:10:00 ERROR - parent: 'vmsNg' }
18:10:00 ERROR -
18:10:00 ERROR - If you are behind a proxy, please make sure that the
18:10:00 ERROR - 'proxy' config is set properly. See: 'npm help config'
18:10:00 INFO -
18:10:00 ERROR - Please include the following file with any support request:
18:10:00 ERROR - /xmake/j/prod-build10010/w/visit-managment-system/visit-managment-system-vmsng-master-CI-linuxx86_64/gen/tmp/src/npm-debug.log
18:10:00 INFO - [2020-02-27 12:40:00] ERROR the "before-all"" build failed: could not execute the "npm install" command: exit status 1
18:10:00 INFO - make: *** [pre_build] Error 1
18:10:00 INFO - Makefile_20200227123846.mta:28: recipe for target 'pre_build' failed
18:10:00 ERROR - could not build the MTA project: could not execute the "make -f Makefile_20200227123846.mta p=CF mtar=vmsNg.mtar strict=true mode= t="/xmake/j/prod-build10010/w/visit-managment-system/visit-managment-system-vmsng-master-CI-linuxx86_64/gen/out"" command: exit status 2
{ [Error: connect ECONNREFUSED]', "11- code: 'ECONNREFUSED',", "12- errno: 'ECONNREFUSED',", "13- syscall: 'connect',", "14- parent: 'vmsNg' }", '15-', '16-If you are behind a proxy, please make sure that the', "17-'proxy' config is set properly. See: 'npm help config'", '18-Please include the following file with any support request:', '19- /xmake/j/prod-build10010/w/visit-managment-system/visit-managment-system-vmsng-master-CI-linuxx86_64/gen/tmp/src/npm-debug.log', '20-[2020-02-27 12:40:00] ERROR the "before-all"" build failed: could not execute the "npm install" command: exit status 1']}
18:10:00 ERROR - xmake ERROR: mbt returned 1
18:10:00 ERROR - ====================================================================================================
18:10:00 ERROR - = workflow failed (--') =
18:10:00 ERROR - archived logs: https://prod-build10000.wdf.sap.corp:443/job/visit-managment-system/job/visit-managment-system-vmsng-master-CI-linuxx86_64/3/artifact/.xmake/logs/build_3_3_workflow.log
18:10:00 ERROR - ====================================================================================================
18:10:00 Build step 'Execute shell' marked build as failure

--------------------------------------------------------------------------------------------------------------

 
Any help  here ?,
Showkath.

**Comment by michawai** [comment]
Hi @Showkath ,
The logs are from internal SAP xMake build system.
Please open a bug in the relevant xMake plugin.
Regards,
Michal
