### ISSUE TITLE
Error in building MTAR xmake

### ISSUE THREAD

**Issue by Showkath** [SAP/cloud-mta-build-tool#704]
Do you want to request a feature or report a bug?

This will be other scenario of already reported issue https://github.com/SAP/cloud-mta-build-tool/issues/703 
for same project 
on  build issue .
As said local build is success using   mbt build -t ./ command but to using xmake
We are using hyper pipe to build mtar  . This hyper-pipe (https://hyper-pipe.tools.sap/)
uses xmake to build MTAR  .Details are below

**### Error 2** created test branch and deleted the npmrc as xmake uses its own npmrc and we were getting issues when downloading the dependencies during npm install. 

https://prod-build10000.wdf.sap.corp/job/visit-managment-system/job/visit-managment-system-vmsng-SP-MS-linuxx86_64/3/console

SP-MS-linuxx86_64/gen/tmp/src/npm-debug.log', '19-[2020-02-27 14:25:19] ERROR the "before-all"" build failed: could not execute the "npm install" command: exit status 1', '20-could not build the MTA project: could not execute the "make -f Makefile_20200227142500.mta p=CF mtar=vmsNg.mtar strict=true mode= t=\\"/xmake/j/prod-build10010/w/visit-managment-system/visit-managment-system-vmsng-SP-MS-linuxx86_64/gen/out\\"" command: exit status 2']}
19:55:19 ERROR - xmake ERROR: mbt returned 1
19:55:19 ERROR - ====================================================================================================
19:55:19 ERROR - = workflow failed (-_-')                                                                           =
19:55:19 ERROR - archived logs: https://prod-build10000.wdf.sap.corp:443/job/visit-managment-system/job/visit-managment-system-vmsng-SP-MS-linuxx86_64/3/artifact/.xmake/logs/build_3_3_build-deploy-workflow.log

Regards,
Showkath.

**Comment by michawai** [comment]
Hi,
The logs are from internal SAP xMake build system.
Please open a bug in the relevant xMake plugin.
Regards,
Michal
