### ISSUE TITLE
Need @sap/hana-client with compilation of latest node version

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP/cloud-mta-build-tool#705]
HI

On My mac machine, I have installed the node version, which is 13.8.0.

When I was building the MTA app, I get the errors due to @sap/hana-client
........
> @sap/hana-client@2.4.162 install /Users/i302342/Documents/sfsf_extensions/SFEXTCAP/cloud-cap-xf-sf-sample-master/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node checkbuild.js

.FATAL ERROR: A fatal error occurred during install.
The module '/Users/i302342/Documents/sfsf_extensions/SFEXTCAP/cloud-cap-xf-sf-sample-master/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 79. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.6: wanted: {"node":">=6.9.1 <=10.16.x"} (current: {"node":"13.8.0","npm":"6.13.7"})
........

How can I get the node module `@sap/hana-client` with compilation of the node version 13.8.0.

Please help me.

Thanks, Manju

**Comment by michawai** [comment]
Hi @manjunathgudisi ,
Please open a ticket in SAP bug tracking system on component HAN-DB-DI.
Regards,
Michal
