### ISSUE TITLE
MTA Deployment fails 

### ISSUE THREAD

**Issue by Thilaknath** [SAP/cloud-mta-build-tool#706]
Cannot retrieve service parameters of service "dom-order-ui-host"#
org.cloudfoundry.client.lib.CloudOperationException: 400 Bad Request: CF-ServiceFetchInstanceParametersNotSupported(120004): This service does not support fetching service instance parameters.
   at org.cloudfoundry.client.lib.CloudControllerClientImpl.convertV3ClientException(CloudControllerClientImpl.java:1056)

Steps to Reproduce:

1. We are deploying our UI application using the Cloud MBT tool in our organization in SAP Cloud platform

Kindly point us to an internal component if it's available for us to open an internal ticket.

**Comment by michawai** [comment]
Hi @Thilaknath ,
Please open a ticket in SAP bug tracking system on component BC-XS-SL-DS.
Regards,
Michal

**Comment by Thilaknath** [comment]
Hi @michawai . The ticket has been opened internally and no one has been assigned to it. Its a blocking issue preventing our release in the next week.

**Comment by I327853** [comment]
Hi @Thilaknath , did this issue get resolved ? I am also facing the same issue while trying to deploy my mtar app from web ide to cf.

Thanks

**Comment by Immanuelbh** [comment]
Hey, not sure if this is relevant or not but I had the same issue. I finally figured out that I had removed modules/apps from the project but they were not removed from the "payload" > "groups" > "payload" > "viz" in the CommonDataModel.json file. Adjusting the file to match the relevant apps in the project resolved my issue and allowed me to deploy.
