### ISSUE TITLE
mbt module-build not working

### ISSUE THREAD

**Issue by sarthak0403** [SAP/cloud-mta-build-tool#707]
Do you want to request a feature or report a bug?
Bug

I'm trying to use the module-build feature. But every time I run the command (mbt module-build -m=<module_name>), I get below error:
[2020-03-09 11:26:35]  INFO building the "" module...
[2020-03-09 11:26:35] ERROR could not get commands for the "" module: the "" module is not defined in the MTA file

For some reason, it's not picking the name of the module from the command.

Please provide the following info:

  - MBT Version: 1.0.10
  - OS Version: Windows OS 1909
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Create an mta.yaml file and describe a module with any name, let's say "module1"
2. run the mbt build command like mbt module-build -m=module1
3. You should get the above error.

**Comment by allaVolkov** [comment]
Issue fixed in release v1.0.11.
