### ISSUE TITLE
How to build mta.yml with docker image as module

### ISSUE THREAD

**Issue by MahatmaFatalError** [SAP/cloud-mta-build-tool#710]
Analog to docker image deployment in mtad.yml (see https://github.com/SAP-samples/cf-mta-examples/tree/master/cf-app-docker) I would like to deploy a docker image via mta.yml.

**Comment by tal-sapan** [comment]
Hi,

You can use the `no-source` build parameter for this, while the rest of the module configuration is the same as in the `mtad.yaml`. See: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-a-module-that-does-not-have-source-code-to-build-and-package

Best regards,
Tal
