### ISSUE TITLE
"The route is invalid: host domain_conflict" when trying to map custom domain without hostname

### ISSUE THREAD

**Issue by 1dEraNCeSIv0** [SAP/cloud-mta-build-tool#713]
**General Problem Description**
We own a custom domain and want to use it to expose our app. According to the documentation host names are only required for shared domains. This is not a shared domain.

Whenever we try to map the custom domain in our mta.yaml deployment to CF fails with the following error:

"Error creating or updating application "APP-NAME": Controller operation failed: 400 Bad Request: CF-RouteInvalid(210001): The route is invalid: host domain_conflict"

Deploying the app without the route and adding it manually works however.

**How to reproduce**
The following was done under Windows 10 using MBT v.1.0.11. I can provide a link to our repository if you contact me via PM, as it's located in SAP's corporate github.

Given a space on cloud foundry with a working app the following steps will reproduce the problem.

1) Create a custom domain without hostname:
`cf create-domain <your-org> custom.<your-default-domain>`
2) Bind the custom domain to your app:
`cf map-route <your-app> custom.<your-default-domain>`
2.a) [Optional] Open custom.\<your-default-domain> in a browser to check that manual mapping exposes your app correctly
3) In the file you're using to define your routes (mta.yaml or *.mtaext) add the following line
`- route: custom.<your-default-domain>`
under modules -> parameters -> routes.
4) Build your app with mbt and deploy it to cloud foundry

Expected outcome:
"Error creating or updating application "APP-NAME": Controller operation failed: 400 Bad Request: CF-RouteInvalid(210001): The route is invalid: host domain_conflict"

**What we've gathered so far**
Given a custom domain like above, the following cf command works as expected:
`cf map-route <app-name> custom.<your-default-domain>`

Given a custom domain like above, the following cf command throws the error we've been getting
`cf map-route <app-name> <your-default-domain> -n custom`

If we replace
`- route: custom.<your-default-domain>`
with
`- route: "*.custom.<your-default-domain>"`
the deployment succeeds. However, we want to expose our app under our custom domain directly.

Due to all of this we suspect that during the deployment process the route defined in the mta.yaml (or *.mtaext) is assumed to begin with a host name. Then the `cf map-route` command is called with the wrong arguments leading to this error.

We neither have nor want to use a host name. Our domain is not shared. According to the cloud foundry documentation host name is an optional field. For all intends and purposes, defining the custom domain route mapping like in the "How to reproduce" section seems correct.

**Comment by tal-sapan** [comment]
Hi @1dEraNCeSIv0 ,

This seems to be an issue in the deployment of the mta and not the build.
Please open a ticket in SAP bug tracking system on component BC-XS-SL-DS.

Best regards,
Tal
