### ISSUE TITLE
Deployment issue - "cannot retrieve service parameters of service ..."

### ISSUE THREAD

**Issue by vraguna** [SAP/cloud-mta-build-tool#717]
Dear Colleagues,

We are facing an issue while deploying the application in CF Integration space. Please find below the error detail and help us to resolve this issue.

"
#2.0#2020 03 24 20:11:27.173#Z#WARN#com.sap.cloud.lm.sl.xs2.83acd96a-6e0b-11ea-a881-eeee0a835b58.MAIN_LOG.DetermineServiceCreateUpdateActionsTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-22###
[DetermineServiceCreateUpdateServiceActionsStep] Cannot retrieve service parameters of service "portal_resources_op"#

org.cloudfoundry.client.lib.CloudOperationException: 400 Bad Request: CF-ServiceFetchInstanceParametersNotSupported(120004): This service does not support fetching service instance parameters.
"
Project MTA file:
https://github.wdf.sap.corp/CSI/outbound_frontend/blob/Variants_mtar_test/mta.yaml#L1

Error Log:
https://github.wdf.sap.corp/CSI/outbound_frontend/blob/Variants_mtar_test/ErrorLog

Regards,
Vinod

**Comment by tal-sapan** [comment]
Hi,

Since the issue is during deployment of the MTAR and not build, please open an internal issue on the CF MTA Deploy Service. I will send you the details by mail.

Best regards,
Tal

**Comment by vraguna** [comment]
Hi Tal,
Thanks for the response. I will raise this issue to "CF MTA Deploy Service" component. 
Regards,
Vinod
