### ISSUE TITLE
Very huge docker image devxci/mbtci

### ISSUE THREAD

**Issue by marcusholl** [SAP/cloud-mta-build-tool#735]
Docker image `devxci/mbtci` is unbelievable huge (1.22GB). This eats-up docker resouces locally and it takes time to materialize the image in docker/kubernetes build environments.

Is there any space for improvement and for reducing the image size?

**Comment by ShimiT** [comment]
Well, the MBT binary size is about 11MB size.
The docker image called mbtci as it intended to support a more complex multi-apps (node/java, etc.)  scenario on the CI environment. 
If you need a smaller image, you can use something like "docker pull devxci/mbtci-alpine", and use it as a base image, in this way, the full control of the image size is on your hand.

**Comment by marcusholl** [comment]
@ShimiT Thanks for responding ...
