### ISSUE TITLE
Incorrect version in created mtad.yaml file

### ISSUE THREAD

**Issue by vinromarin** [SAP/cloud-mta-build-tool#736]
Bug or question.

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. - done
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 
(xMake is used)

I'm building MTA app with UI5 module via internal xMake system.

Steps to Reproduce:

1. GitHub repo with UI5 module. Created app should be deployed into NEO.
2. Created mta.yaml file contains version parameter two times (in accordance with documentation both are required):
![image](https://user-images.githubusercontent.com/23128319/80982716-fc8c1c00-8e2b-11ea-9333-771ae4d7f9c9.png)

 
3. After using of Piper library and xMake with Cloud Mta builder i expect to get mtar file with created mtad.yaml file where BOTH versions should be updated (suffix with timestamp and commitid should be added to the versions). It worked so several days ago. 
But now only one version is updated in mtad.yaml:
![image](https://user-images.githubusercontent.com/23128319/80982605-d8c8d600-8e2b-11ea-97f0-c8f0996b4c8d.png)

Could you please help to understand the reason for this behaviour? 
Did you update mta builder recently?

Thank you and best regards,
Marina

**Comment by katunin-ng** [comment]
Hi,
The Cloud MTA Build tool does not have a feature that updates a version in the mtad,yaml during the build. 
Probably the behavior that you describe is implemented in the tools that trigger the build, e.g. piper. Therefore, please open a  ticket in their issue tracking systems.
Regards
Natalia
