### ISSUE TITLE
How to generate mta.yml file in CAP Project

### ISSUE THREAD

**Issue by sam907reddy** [SAP/cloud-mta-build-tool#737]
Hi Team,
We are using CAP model java application with V4 Odata service FE project . Development is VS code. Installed MBT tool and we want to make Cap based FE project as a MTA. while executing command "mbt build" I’m getting below error. 
please help me

![image](https://user-images.githubusercontent.com/65271168/81772704-29af8d00-9504-11ea-95d5-481a598c5ed9.png)

**Comment by katunin-ng** [comment]
Hi,

Please check this documentation:  https://cap.cloud.sap/docs/advanced/deploy-to-cloud#deploy-using-mta for the details on how to add the mta.yaml file to a CAP project.

Regards
Natalia

**Comment by sam907reddy** [comment]
Hi i added mta.yml file but still im notable to generate the build command 

![image](https://user-images.githubusercontent.com/65271168/81785970-a5b5cf00-951c-11ea-8bf5-51f1b8887f36.png)

**Comment by katunin-ng** [comment]
Hi,

I see.
You need to install GNU Make on your machine as described here:  https://sap.github.io/cloud-mta-build-tool/makefile/

Regards
Natalia

**Comment by sam907reddy** [comment]
i installed required exe file.

**Comment by katunin-ng** [comment]
Hi,

If installed the GNU Make and updated the PATH environment variable as described, please try to run the command from the new CLI. It seems the environment variable changes were not propagated to the opened CLI/terminal.

Regards
Natalia

**Comment by sam907reddy** [comment]
i did setup like this let me know if i did any mistake ?

![image](https://user-images.githubusercontent.com/65271168/81791194-0694d580-9524-11ea-8be7-b4ee78e1e367.png)

**Comment by tal-sapan** [comment]
Hi @sam907reddy,

Please check that you updated the `Path` environment variable by adding the folder that the `make.exe` file is in to it.

![image](https://user-images.githubusercontent.com/13255544/81794781-f70d9080-9513-11ea-8430-9159e68df878.png)

**Comment by soumya7** [comment]
I was facing same issue, then realized that downloaded file name is mbt.exe. Renaming it to make.exe fixed the issue.

**Comment by afuscella** [comment]
@katunin-ng it worked for me

thanks! gg
