### ISSUE TITLE
issue while adding UI and db modules 

### ISSUE THREAD

**Issue by sam907reddy** [SAP/cloud-mta-build-tool#739]
Hi Team,

We are using CAP model java application with V4 Odata service FE project . Development ID is VS code.
Required installations done.
Creating mta file using "cds add mta" command and it is generating with basic srv model. With is mta im able to build mtar file and deploying cf . but only service metadata is deploying.

Now I understand in mta file we need to add UI modules and db modules manually to create mtar file.
While adding this modules im facing path error and don’t know proper steps what need to add for each modules.

Please let me know any document how add modules or what are the step need to taek care to create mta.yaml file ?

my MTA.yaml file 👎 

## approuter=
_schema-version: '3.1'
ID: IRPManagePosting
version: 1.0.0
description: "A simple CAP project."
parameters:
  enable-parallel-deployments: true
  deploy_mode: html5-repo
  
  
build-parameters:
  before-all:
   - builder: custom
     commands:
      - npm install
      - npx cds build

modules:
  #####################################################################################################################
  # Database
  #####################################################################################################################
 - name: IRPManagePosting-db
    type: hdb
    path: gen/db
    requires:
      - name: IRPManagePosting-hdi-container
    parameters:
      memory: 64M
      disk-quota: 128M
    build-parameters:
      ignore: ["_i18n/"]

 # --------------------- SERVER MODULE ------------------------
 - name: IRPManagePosting-srv
 # ------------------------------------------------------------
   type: nodejs
   path: gen/srv
   properties:
     EXIT: 1  # required by deploy.js task to terminate 
 #####################################################################################################################
  # Apps
 #####################################################################################################################
 - name: IRPManagePosting-app
    type: html5
    path: app
    build-parameters:
      builder: custom
      commands:
        - npm install
        - npm run build
  
      supported-platforms: []
      build-result: dist

Error:
![image](https://user-images.githubusercontent.com/65271168/81907067-d5300e80-95e4-11ea-875f-290f883e4c4e.png)

**Comment by katunin-ng** [comment]
Hi,
Since your questions are not about the Cloud MBT Tool features, but about the Cloud Application Programming Model, please post them in this community:
https://community.sap.com/topics/cloud-application-programming 
Regards
Natalia
