### ISSUE TITLE
cloud mta tool not accepting 4 decimal version

### ISSUE THREAD

**Issue by trimbandaru007** [SAP/cloud-mta-build-tool#741]
Hi Team,

I am from SAP and using mta builder projects quite some time.
Recently all our builds failing if you if we have mta verion with 4 decimals.
ex: 2.7.9.1

We need 4th decimal to release hot fixes but build tool not accepting.

Please let me know if you need more details.
It would be great if we have direct contact to discuss in detail.

Below is the build error

---
 [2020-05-20 06:38:43]  INFO Cloud MTA Build Tool version 1.0.14
12:08:43 INFO - [2020-05-20 06:38:43]  INFO generating the "Makefile_20200520063843.mta" file...
12:08:43 INFO - [2020-05-20 06:38:43]  INFO done
12:08:43 INFO - [2020-05-20 06:38:43]  INFO executing the "make -f Makefile_20200520063843.mta p=NEO mtar=SLH-ACRS-ONDEMAND-SOLUTION.mtar strict=true mode= t=\"/xmake/j/prod-build10110/w/srf-as-a-service/srf-as-a-service-slh-acrs-mtar-SP-MS-linuxx86_64-linuxx86_64/gen/out\"" command...
12:08:43 INFO - [2020-05-20 06:38:43]  INFO validating the MTA project
12:08:43 INFO - [2020-05-20 06:38:43] ERROR the "mta.yaml" file is not valid: 
12:08:43 INFO - line 3: the "2.7.9.1-20200520063456+70f50f644f1fd3e56a681939b4643df02c1296ca" value of the "root.version" property does not match the "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$" pattern
12:08:43 INFO - Makefile_20200520063843.mta:26: recipe for target 'pre_validate' failed

----

Thanks
-Trim

**Comment by michawai** [comment]
Hi Trim,
According MTA schema only <Major_Version>.<Minor_Version>.<Patch_Version> pattern is allowed.
Regards,
Michal

**Comment by trimbandaru007** [comment]
Hi @michawai ,

Thanks for the response.
This 4 decimal version is working few months back. but suddenly stopped supporting. any specific reason for this? can we control version pattern through any configuration?

Thanks
-Trim

**Comment by michawai** [comment]
Hi,
Cloud MBT is aligned with MTA schema and only version format x.y.z is supported.
Regards,
Michal
