### ISSUE TITLE
Supported module types

### ISSUE THREAD

**Issue by kepair** [SAP/cloud-mta-build-tool#742]
### Description

I work at SAP providing support for SCP.
In many examples I see that they use `approuter.nodejs` module type ([here](https://help.sap.com/viewer/0e4dd38c4e204f47b1ffd09e5684537b/Cloud/en-US/e8059587e95a407f91d2dcf5b11568d5.html) for example). 

I've checked the [MTA model document](https://www.sap.com/documents/2016/06/e2f618e4-757c-0010-82c7-eda71af511fa.html) where they say they support `nodejs` "and more".

I still haven't found a complete list with supported module types.

Is there a place where I can see what SCP CF accepts as module type?
Does using `approuter.nodejs` instead of `nodejs` have any implications?
If this is not the place, can you point me to where I can find this information?

### My environment
*	Cloud MTA Build Tool version 1.0.12
*	MultiApps CF CLI Plugin version - 2.3.1
*	which CF vendor is used - SAP CF

Thanks,
Pedro

**Comment by katunin-ng** [comment]
Hi Pedro,
You can find a complete list of SCP CF module types [here](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/177d34d45e3d4fd99f4eeeffc5814cf1.html).

These are types that are supported by the deploy service when you deploy an MTA archive (mtar) created by the build tool.  You can use any of these types directly in the design-time MTA project descriptor, the mta.yaml file. By default, during the build, the build tool will just create a zip archive from the module's folder and package it into the result mtar, the module definition will be copied to the deployment descriptor, the mtad.yaml file, "as is".  You can change this default build behavior by configuring [build parameters](https://sap.github.io/cloud-mta-build-tool/configuration/#overview) in the mta.yaml file.

There are also module types "known" to the build tool only. A module of such type will be built using a predefined builder (if not configured differently in the build-parameters).  For the complete list of available builders and their default behaviors, see [here](https://github.com/SAP/cloud-mta-build-tool/blob/master/configs/builder_type_cfg.yaml). To find out which builder is applied to a module by default see [here](https://github.com/SAP/cloud-mta-build-tool/blob/master/configs/module_type_cfg.yaml). Also, in the deployment descriptor, the design-time modules are converted into the module types of the corresponding target platform according to this [mapping](https://github.com/SAP/cloud-mta-build-tool/blob/master/configs/platform_cfg.yaml). 

In your example, both types are design-time types. They both are built using "npm" builder and translated to "javascript.nodejs" deployment type in mtad.yaml. So for the build tool, it does not matter which type is used. However, there could be other design-time tools, e.g. IDE editors,  that handle these types differently. I do not have details about these tools.

I hope it clarifies the "module type" topic.

Regards
Natalia
