### ISSUE TITLE
Docker image update for the piper project

### ISSUE THREAD

**Issue by maxx1e** [SAP/cloud-mta-build-tool#743]
There is https://sap.github.io/jenkins-library/configuration/ project available. It contains set of [Docker images](https://github.com/SAP/devops-docker-mta-archive-builder/blob/master/Dockerfile). One of the images available there is ol MTA builder. Will be great if that image will be replace with new one that will contain new cloud MTA builder.

**Comment by michawai** [comment]
Please contact repo contributors to update the MTA builder.
