### ISSUE TITLE
MTA build failed, possible lack of root permission

### ISSUE THREAD

**Issue by airyangfan** [SAP/cloud-mta-build-tool#744]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: 1.0.14
  - OS Version: Ubuntu 16.04.6 LTS
  - If possible, provide a link to the project.

Steps to Reproduce:

1. stage('Build')   {
      mtaBuild script:this
  }

Hi,

I tried to build my mta by using piper. The project has been setup correctly. And it could be built successfully in local by using:
`sudo mtb build -p neo`

However, when i trigger the build by Jenkinsfile, I always have the error:

info  mtaBuild - npm registry @sap:registry was not configured, setting it to https://npm.sap.com
info  mtaBuild - running command: npm config set @sap:registry https://npm.sap.com
info  mtaBuild - "mta.yaml" file found in project sources
info  mtaBuild - No timestamp contained in "mta.yaml". File has not been modified.
info  mtaBuild - Executing mta build call: "mbt build --mtar coe_alm_test_advisory_demo_mta.mtar --platform NEO --target ./"
info  mtaBuild - running command: mbt build --mtar coe_alm_test_advisory_demo_mta.mtar --platform NEO --target ./
info  mtaBuild - [2020-06-11 04:04:12]  INFO Cloud MTA Build Tool version 1.0.14
info  mtaBuild - [2020-06-11 04:04:12]  INFO generating the "Makefile_20200611040412.mta" file...
info  mtaBuild - [2020-06-11 04:04:12]  INFO done
info  mtaBuild - [2020-06-11 04:04:12]  INFO executing the "make -f Makefile_20200611040412.mta p=NEO mtar=coe_alm_test_advisory_demo_mta.mtar strict=true mode= t=\"./\"" command...
info  mtaBuild - [2020-06-11 04:04:12]  INFO validating the MTA project
info  mtaBuild - [2020-06-11 04:04:12]  INFO validating the MTA project
info  mtaBuild - [2020-06-11 04:04:12]  INFO building the "coe_alm_test_advisory_demo" module...
info  mtaBuild - [2020-06-11 04:04:12]  INFO executing the "npm install --production" command...
info  mtaBuild - ....................
info  mtaBuild - > core-js@2.6.11 postinstall /var/lib/jenkins/workspace/Test_Advisory_Demo/TA_Test_Build/node_modules/@ui5/cli/node_modules/core-js
info  mtaBuild - > node -e "try{require('./postinstall')}catch(e){}"
info  mtaBuild - 
warn  mtaBuild - npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/@ui5/cli/node_modules/fsevents):
warn  mtaBuild - npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
info  mtaBuild - 
info  mtaBuild - .added 749 packages from 740 contributors and audited 812 packages in 20.599s
info  mtaBuild - .
info  mtaBuild - 22 packages are looking for funding
info  mtaBuild -   run `npm fund` for details
info  mtaBuild - 
info  mtaBuild - found 11 vulnerabilities (9 low, 2 high)
info  mtaBuild -   run `npm audit fix` to fix them, or `npm audit` for details
info  mtaBuild - [2020-06-11 04:04:34]  INFO the build results of the "coe_alm_test_advisory_demo" module will be packaged and saved in the ".TA_Test_Build_mta_build_tmp/coe_alm_test_advisory_demo" folder
error mtaBuild - [2020-06-11 04:04:34] ERROR could not package the "coe_alm_test_advisory_demo" module while getting the build artifact: could not find the "/var/lib/jenkins/workspace/Test_Advisory_Demo/TA_Test_Build/dist" path
info  mtaBuild - Makefile_20200611040412.mta:37: recipe for target 'coe_alm_test_advisory_demo' failed
info  mtaBuild - make: *** [coe_alm_test_advisory_demo] Error 1
info  mtaBuild - Error: could not build the MTA project: could not execute the "make -f Makefile_20200611040412.mta p=NEO mtar=coe_alm_test_advisory_demo_mta.mtar strict=true mode= t=\"./\"" command: exit status 2
fatal mtaBuild - failed to execute mta build - running command 'mbt' failed: cmd.Run() failed: exit status 1
[Pipeline] fileExists
[Pipeline] readJSON
[Pipeline] error
[Pipeline] libraryResource
[Pipeline] echo
----------------------------------------------------------
--- An error occurred in the library step: dockerExecute
----------------------------------------------------------
The following parameters were available to the step:
***
*** to show step parameters, set verbose:true in general pipeline configuration
*** WARNING: this may reveal sensitive information. ***
***
The error was:
***
hudson.AbortException: [mtaBuild] Step execution failed. Error: running command 'mbt' failed: cmd.Run() failed: exit status 1

Jenkins service and npm both have root permission. I suppose it's a permission issue but I don't know how to build mta by piper under root permission.

Thanks a lot for your help.
Fan

I attached Jenkinsfile, mta.yaml and config.yml.
[demo.zip](https://github.com/SAP/cloud-mta-build-tool/files/4765673/demo.zip)

**Comment by tal-sapan** [comment]
Hi,

The error root cause is: 
`could not package the "coe_alm_test_advisory_demo" module while getting the build artifact: could not find the "/var/lib/jenkins/workspace/Test_Advisory_Demo/TA_Test_Build/dist" path`
Please check that this folder is created during the build.

Best regards,
Tal

**Comment by airyangfan** [comment]
Hi Tal,

Thanks a lot for your reply.

The path did not exist. However, I still cannot understand why it was trying to find this path "TA_Test_Build/dist". When I built locally (by using mbt build directly), the package was built in "/mta_archives" file. Is it something pre-packaged in piper? 

Thank you!
Fan

**Comment by tal-sapan** [comment]
Hi,

The path is to the build results of the module. It's defined under the `build-parameters` as `build-result: dist`. If this is not where the build results of the module are created, please change the path to the build results path (relative to the module's path).
It's possible that in your local build you had this folder as a left over of a previous build so you didn't get the error.
The `mtar` file will still be created under `mta_archives`.

Best regards,
Tal

**Comment by airyangfan** [comment]
Hi Tal,

Thanks a lot for your message. You're completely right and I fixed the issue.

Thank you and best regards,
Fan
