### ISSUE TITLE
Issue while running mbt build..Cannot find module "@sap/node-jwt/build.js"

### ISSUE THREAD

**Issue by sooraj2589** [SAP/cloud-mta-build-tool#751]
After successfully installed mbt, I have tried to run mbt build on my project code. But its getting below error

Error: Cannot find module '/root/MTA/DevOpsSample/node_modules/@sap/node-jwt/build.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
.npm WARN DevOpsSample@0.0.1 No description
npm WARN DevOpsSample@0.0.1 No repository field.
npm WARN DevOpsSample@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sap/node-jwt@1.6.9 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @sap/node-jwt@1.6.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-16T08_47_03_757Z-debug.log
[2020-06-16 08:47:03] ERROR could not build the "DevOpsSample" module: could not execute the "npm install" command: exit status 1
Error: could not build the MTA project: could not execute the "make -f Makefile_20200616084642.mta p=cf mtar= strict=true mode=" command: exit status 2

Could anyone please help?

**Comment by tal-sapan** [comment]
Hi,

Could you check if you get this error when running `npm install` in the module folder (of module `DevOpsSample`)?

Thanks,
Tal

**Comment by sooraj2589** [comment]
Yes got the **same error** after running npm install in the module folder

**Comment by katunin-ng** [comment]
HI @sooraj2589,
This is not the MBT issue, it relates to the npm packages that you are using in your module.
What is the type of problematic module? Do you use the auto-generated content or add dependencies/scripts of your own?
Regards
Natalia

**Comment by sooraj2589** [comment]
module name @sap/node-jwt..This is missing to find.  We are using only auto generated content.

**Comment by katunin-ng** [comment]
Hi @sooraj2589, I meant the type of DevOpsSample MTA module as defined in the mta.yaml file. @sap/node-jwt is an npm package this module has a dependency specified in the module's package.json. Once I know what the MTA module type is, I can refer you to the relevant colleagues. 
Regards
Natalia

**Comment by sooraj2589** [comment]
Hi @katunin-ng, got it. In mta.yaml file I could see the module type is **html5**

**Comment by katunin-ng** [comment]
@avizov could you please have a look at the issue. the html5 module build fails.
Thank you
Natalia

**Comment by sooraj2589** [comment]
@avizon any update on this issue?

**Comment by avizov** [comment]
I am not sure how the fact that it is a grunt builder relates to the error you got. Your failing is a simple npm install failing that indicates that the specific npm module doesn't exist in the registered npm.

**Comment by sooraj2589** [comment]
What will be the solution? the error is getting as " cannot find module @sap/node-jwt/build.js"

**Comment by avizov** [comment]
pls add github link

**Comment by sooraj2589** [comment]
@avizov, https://github.com/anuwilson137/scppoc/tree/dev

**Comment by avizov** [comment]
I successfully did a build, locally and within webidecp-fiori account. So, where is the issue?
Locally:
![image](https://user-images.githubusercontent.com/12681057/85298399-b27afa80-b4ac-11ea-92af-a3870009a5b9.png)

webidecp-fiori:
![image](https://user-images.githubusercontent.com/12681057/85298535-e35b2f80-b4ac-11ea-9268-fe80d57f2505.png)

**Comment by sooraj2589** [comment]
Which command you used?  I have tried with mbt build -p=cf. Then glt that module error.

Can you please tell the build commands and steps you tried?

**Comment by avizov** [comment]
mbt build

**Comment by sooraj2589** [comment]
Same tried with error.  Have you installed any node module?

**Comment by avizov** [comment]
just mbt build

**Comment by avizov** [comment]
this is my mbt tool version
Cloud MTA Build Tool version 1.0.14

**Comment by sooraj2589** [comment]
Same version using.. mbt build failed with this error

**Comment by avizov** [comment]
therefore, I am not sure what is the issue and how I can help here. In general, npm installs everything that in your package.json file. I took your repo as u shared, clone it, and checkout to dev branch then performed mbt build. Everything worked fine for me.

**Comment by sooraj2589** [comment]
what is your node npm version?

**Comment by katunin-ng** [comment]
Hi,

I also managed to build the project successfully on my machine. 
Since the module build commands fail when run directly in the module folder, it is not the MBT failure. Unfortunately, the MBT colleagues are not npm experts and cannot assist much with the problem. Therefore, I am closing the issue.
Please try to clone the project in the new location and rebuild.
Regards
Natalia

**Comment by ShimiT** [comment]
@sooraj2589 - Are you pointing to the right npm registry? (.npmrc)

**Comment by sooraj2589** [comment]
Thank you.

@ShimiT Yes.
