### ISSUE TITLE
MTA Ignore Pramameter Has No Effect

### ISSUE THREAD

**Issue by borceacristiann** [SAP/cloud-mta-build-tool#755]
Dear Colleagues,  

We are using MTA build tool to package our SAP UI5 application into a mtar and deploy it to Cloud Foundry. The mta.yaml file was created by following the documentation https://sap.github.io/cloud-mta-build-tool/configuration/ . The build parameter "ignore" was used to exclude some folders and files from our src folder, unfortunately this has no effect.

The structure of our project is the following:

Etd-Cloud-Ui-Application:
- Build (minified & uglified content);
- Deployer (HTML5 application content);
- Src (webapp);
- Src/test
- mta.yaml

We tried the following combinations:   "./src/test", ".src/test/","./src/test/**", "**/test/**", "/test/**", "test/**", "/test/" , "test/" but none of them seem to work :(

Please find attached a copy of mta.yaml.

- MBT Version: 1.0.14;
- OS Version: Win 10 & MAC OS Catalina.

What is the best approach to ignore a file from the source folder?

Regards,
Borcea Cristian.

[MTA_FILE.txt](https://github.com/SAP/cloud-mta-build-tool/files/4835720/MTA_FILE.txt)

**Comment by katunin-ng** [comment]
Hi,

The ‘ignore’ build configuration is applied when a module is packaged into mtar. Html5 module in your application is not packaged. Its content is copied to the deployer module and it is the deployer module that is actually added to the mtar. If you need to exclude files you need to configure the ‘ignore’ option in the deployer module.

Regards
Natalia

**Comment by borceacristiann** [comment]
thank you very much :)
