### ISSUE TITLE
Can't install the MBT via NPM due to Header Check Issues

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/cloud-mta-build-tool#758]
Hi colleagues,

In my project, I'm installing the mbt through npm and even have it in my ci/cd pipeline installed via npm. Since this morning (8:30 MESZ), in the pipeline the installation is failing. I was able to produce this error locally as well:

```
> mbt@1.0.15 install C:\Users\xxx\dev\tmp\mbt-test\node_modules\mbt
> binwrap-install

ERR Error decompressing https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.15/cloud-mta-build-tool_1.0.15_Windows_amd64.tar.gz Error: incorrect header check
```

A minimal working example for me was just 4 commands:

```
mkdir mbt-test
cd mbt-test
npm init --yes

npm i mbt
> failure
```

As you can see, I'm on Windows 10, but the pipeline is on Linux:

```
ERR Error decompressing https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.15/cloud-mta-build-tool_1.0.15_Linux_amd64.tar.gz Error: incorrect header check
```

The interesting thing is that the issue also occurs in my MWE, when I install an older version like `npm i mbt@1.0.14`.

Thank you very much for your help in resolving this!
Kind regards
Lukas

**Comment by LukasHeimann** [comment]
It looks like the issue somehow resolved itself.
Do you know what the root-cause of this was? How can we debug issues like this in the future?

**Comment by lidortal** [comment]
Hi @LukasHeimann, it looks like GitHub was down, see here: https://www.githubstatus.com/incidents/j597fw8kv04c?utm_ts=1594629104

**Comment by michawai** [comment]
It sounds like temporary issue with npm. 
Not related to mbt.
