### ISSUE TITLE
Bundler bundles outdated JAR from Maven Builder

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/cloud-mta-build-tool#759]
Hi everyone!

In my project, I'm having Java modules within an MTA archive. I'm building those with the default Maven builder.

The default config, however, does only run `mvn -B package`, and not the `clean` goal. This causes, after a change in the pom version, multiple `jar` files to be present in the `target` folder - of which only the first, meaning the one with the lower version number, is copied over to the mtar. The newly built version is not included.

This is bad, as there are many Java services in my MTA (so I don't want to clean each of them individually) and I don't want to deviate from the defaults provided by the MBT too much.

Please consider adapting the default behavior by either
- choosing the latest/newest artifact matched by the `build-result` (in my case the latest `target/*.jar`), e.g. by the last changed date
- adapting the default command to `mvn clean package`

Thank you very much for your support!
Kind regards
Lukas

Please provide the following info:

  - MBT Version: 1.0.14
  - OS Version: Windows 10

**Comment by katunin-ng** [comment]
Hi Lukas,

As the current maven builder is used by multiple users we cannot change its behavior easily.
Please consider using a 'custom' builder for your module instead and define commands that satisfied your needs as described here: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder.

Regards
Natalia

**Comment by katunin-ng** [comment]
Hi @LukasHeimann,
I have discussed the topic with the experts and we are planning to implement your proposal (adapting the default command to mvn clean package)
Please track the release notes for the update.
Thank you for the idea.
Natalia
