### ISSUE TITLE
Module type "siteentry" should be converted to javascript.nodejs

### ISSUE THREAD

**Issue by RafaelYegrosTR** [SAP/cloud-mta-build-tool#762]
Bug Report

   I believe that modules of type "siteentry" should be converted to "javascript.node js" at packing stage. Similar to what was did to site-content at bug:
https://github.com/SAP/cloud-mta-build-tool/commit/36d44afc1e74b068b609504cb548992684c9faee

Ps. I don´t know if convert the "type" will be enough to fix this issue, but looks like a good start.

  - MBT Version: 1.0.15
  - OS Version: Linux Redhat 7.5
  - Target System: XSA

Steps to Reproduce:

1. Using XSA SAPWebIDE, create the sample project as described in https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.04/en-US/69fd5fc904fd4467b85818b501459ac9.html
2. Export the project to your machine.
3. Use MBT to pack it.
4. Try to deploy on XSA Space trough "xs deploy" , the follow error will appear:
`
Error merging descriptors: Unsupported module type "siteentry" for platform type "XSA"
Unexpected error: Unsupported module type "siteentry" for platform type "XSA"
Exception occured during execution: "Unsupported module type "siteentry" for platform type "XSA""
ERR    Error merging descriptors: Unsupported module type "siteentry" for platform type "XSA"
Unexpected error: Unsupported module type "siteentry" for platform type "XSA"
Exception occured during execution: "Unsupported module type "siteentry" for platform type "XSA""
`

**Comment by katunin-ng** [comment]
Hi,

Unfortunately, the scenario that you describe is not supported. To build your application, you need to follow the steps described in the document: https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.04/en-US/69fd5fc904fd4467b85818b501459ac9.html. 

Regards
Natalia
