### ISSUE TITLE
User namespace issue while running mbtci image in Jenkins agent

### ISSUE THREAD

**Issue by anuwilson137** [SAP/cloud-mta-build-tool#769]
--- An error occurred in the library step: dockerExecute

Error: docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused **"cannot set uid to unmapped user in user namespace"**: unknown.

**Comment by tal-sapan** [comment]
Hi,

Do you still encounter this issue?

Best regards,
Tal

**Comment by michawai** [comment]
Closing as there's no response for a long period.
