### ISSUE TITLE
[doc] Reference to outdated SAP npm registry 

### ISSUE THREAD

**Issue by ChrisRBecker** [SAP/cloud-mta-build-tool#771]
Dear colleagues,

In your documentation, you refer to the SAP-specific registry for npm packages of the @sap namespace (npm.sap.com), e.g. in the Troubleshooting section (https://sap.github.io/cloud-mta-build-tool/troubleshooting/). While this registry still exists, it has been deprecated and shall not be used anymore in the future. New versions of the SAP packages won't be published there anymore. 

Please refer to this blog post, for example: https://blogs.sap.com/2020/07/02/sap-npm-packages-now-on-npmjs.org/ 

Best regards
Christian

**Comment by katunin-ng** [comment]
@ChrisRBecker thank you for reporting the issue. We have just removed the section that is not relevant anymore from the doc.
