### ISSUE TITLE
Allow anonymous pulls of `devxci/mbtci` after DockerHub's rate limiting is in effect

### ISSUE THREAD

**Issue by fwilhe** [SAP/cloud-mta-build-tool#775]
Docker [announced rate limiting](https://www.docker.com/pricing) for images located on Docker Hub effective November 1st 2020.

This might be an issue for CI usage of [devxci/mbtci](https://hub.docker.com/r/devxci/mbtci), depending on how the image is cached and how often a "pull" happens (see [How is a pull request defined for purposes of rate limiting?](https://www.docker.com/pricing/resource-consumption-updates) for details on how "pulls" are counted). This issue can be in part mitigated by logging into DockerHub, and for users of project "Piper" we will work on options to do that. Still there might be cases where this forces users to buy a DockerHub subscription.

One possible alternative would be to **in addition to Docker** Hub also publish the image to [GitHub's newly announced Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) which _seems_ to allow anonymous pulls without rate limiting (at least I was not able to find any indicators for this so far).

There might be other alternatives I'm not aware of now.

Opinions?

**Comment by katunin-ng** [comment]
Hi Florian, @fwilhe 
Thank you for the heads up!
We need to investigate and discuss the topic internally. We will keep you updated.
Regards
Natalia

**Comment by michawai** [comment]
Hi,
We published mbtci image in github: 
https://github.com/SAP/cloud-mta-build-tool/packages/445909/versions
https://github.com/SAP/cloud-mta-build-tool/packages/473756/versions
See our [README](https://github.com/SAP/cloud-mta-build-tool/blob/docker/README.md)
Regards,
Michal

**Comment by fwilhe** [comment]
Hi @michawai 

thanks for letting me know. Just fyi, there are two ways to publish Docker images at github, it looks like you chose the older one that is "deprecated". Not sure if this is on purpose.

![image](https://user-images.githubusercontent.com/2292245/97872897-1349f780-1d17-11eb-94b6-4fae52cbcc06.png)

This is the "new one": [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

We're using that in project "Piper" and it seems to work great as far as I can tell so far, cf https://github.com/SAP/devops-docker-cx-server/commit/7adab306ee12244431f448332754313b40416725

Best,

Florian
