### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sumnthegade** [SAP/cloud-mta-build-tool#785]
Hi Team,

I have observed the below error while building the mtar for my project using mta  configuration file.
[2020-10-01 13:47:02]  INFO finished building the "web" module
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x74c51a]

goroutine 1 [running]:
github.com/SAP/cloud-mta-build-tool/internal/artifacts.copyMtaContentFromPath(0xc0000a4500, 0x35, 0xc0000ca120, 0x51, 0xc000087ca0, 0x17, 0xc0000a4400, 0x39, 0x0, 0x0, ...)
        /Users/i056926/projects/cloud-mta-build-tool/internal/artifacts/module_arch.go:572 +0x5a
github.com/SAP/cloud-mta-build-tool/internal/artifacts.copyMtaContent(0xc0000860c0, 0x1d, 0xc0000a4400, 0x39, 0xc0000f3620, 0x1, 0x1, 0x0, 0xc0000e08e0, 0x1b)
        /Users/i056926/projects/cloud-mta-build-tool/internal/artifacts/module_arch.go:551 +0x27e
github.com/SAP/cloud-mta-build-tool/internal/artifacts.copyResourceContent(0xc0000860c0, 0x1d, 0xc0000a4400, 0x39, 0xc00009e1a0, 0x0, 0x0, 0x0)
        /Users/i056926/projects/cloud-mta-build-tool/internal/artifacts/module_arch.go:517 +0xae
github.com/SAP/cloud-mta-build-tool/internal/artifacts.execProjectBuilders(0xc0000a6060, 0xc00009e1a0, 0xc00001815b, 0x4, 0xa26452, 0x0)
        /Users/i056926/projects/cloud-mta-build-tool/internal/artifacts/project.go:103 +0xe9
github.com/SAP/cloud-mta-build-tool/internal/artifacts.ExecuteProjectBuild(0x0, 0x0, 0xc00001e363, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00001815b, ...)
        /Users/i056926/projects/cloud-mta-build-tool/internal/artifacts/project.go:95 +0x1fc
github.com/SAP/cloud-mta-build-tool/cmd.glob..func15(0xece740, 0xc000092060, 0x0, 0x2, 0x0, 0x0)
        /Users/i056926/projects/cloud-mta-build-tool/cmd/project.go:36 +0xca
github.com/spf13/cobra.(*Command).execute(0xece740, 0xc000092040, 0x2, 0x2, 0xece740, 0xc000092040)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x45a
github.com/spf13/cobra.(*Command).ExecuteC(0xecec80, 0x0, 0x9648c0, 0xc000026118)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/i056926/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/SAP/cloud-mta-build-tool/cmd.Execute(...)
        /Users/i056926/projects/cloud-mta-build-tool/cmd/root.go:33
main.main()
        /Users/i056926/projects/cloud-mta-build-tool/main.go:11 +0x35
make: *** [Makefile_20201001134636.mta:42: post_build] Error 2
Error: could not build the MTA project: could not execute the "make -f Makefile_20201001134636.mta p=cf mtar= strict=true mode=" command: exit status 2
could you please let me know why i am getting the above error and help me to resolve the above error

**Comment by allacherkes** [comment]
Hi, 
If it is possible, can you please provide your project, so we can investigate the problem.
Thanks

**Comment by katunin-ng** [comment]
Hi,
There are no activities in this thread for 2 weeks. I am closing the issue.
Feel free to reopen if needed.
Regards
Natalia
