### ISSUE TITLE
Setting relative path for mta.yaml

### ISSUE THREAD

**Issue by anuwilson137** [SAP/cloud-mta-build-tool#790]
Should the mta.yaml file be present in the root directory itself? 
I tried giving its relative file in config.yaml but it is not working. Is there any way I can mention the relative path for mta.yaml file?

**Comment by allacherkes** [comment]
Hi,
Can you please elaborate more regarding your use case? 
Thanks.

**Comment by katunin-ng** [comment]
There are no activities in this thread for 2 weeks. I am closing the issue.
Please re-open if needed.
Regards
Natalia
