### ISSUE TITLE
How to specify the path of mta.yaml file while running mtabuild?

### ISSUE THREAD

**Issue by sooraj2589** [SAP/cloud-mta-build-tool#794]
I have mta.yaml file in a folder. How can I specify the path of mta file while running build command mtabuild?

could any one help please?

**Comment by tal-sapan** [comment]
Hi,

You can specify the path to the folder of the `mta.yaml` file with the `-s` (or `--source`) option.
See more details in [the documentation](https://sap.github.io/cloud-mta-build-tool/usage/#one-step-build).

**Comment by andre68723** [comment]
@tal-sapan Is it also somehow possible to specify the filename different from mta.yaml?

Thinking of scenarios were different modules are required which cannot be overwritten by mtaext like
here for single/mt - https://github.com/SAP-samples/cloud-cap-samples-java#deploy-to-sap-business-technology-platform

**Comment by katunin-ng** [comment]
@sooraj2589 currently we do not plan to provide a possibility to specify the filename different from mta.yaml.
If you have different modules to be packaged into the MTA archive in different scenarios, you need to define all of them in the mta.yaml and control what module to exclude by empty "supported-platforms" build option in mtaext file: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-and-packaging-modules-according-to-target-platforms - see module C in the example.

Regards
Natalia

**Comment by andre68723** [comment]
Hi Natalia,

can you please eloborate on how that would help with same platform (CF) and especially  with respect to resources?

Thanks, Andre

**Comment by katunin-ng** [comment]
Hi, 
Please check the attached file. I tried to illustrate the solution for both modules and resources. [sample.txt](https://github.com/SAP/cloud-mta-build-tool/files/6341850/sample.txt)

Regards
Natalia

**Comment by andre68723** [comment]
Thanks Natilia, appreciate your efforts. 

Was not aware that resources could be made inactive.
