### ISSUE TITLE
Support LTS 14 of node.js

### ISSUE THREAD

**Issue by rotda** [SAP/cloud-mta-build-tool#799]
Hello together ,

the new LTS of Node.js is 14 and not 12.
We are using Azure DevOps for CI/CD and they switch to LTS 14 and so the build's are not running anymore.

https://github.com/actions/virtual-environments/issues/1953

is there a plan for 14 ? If I get it right 12 will be end of maintenance End of Nov

Error :
```

[2020-11-05 09:52:15]  INFO Cloud MTA Build Tool version 1.0.16
[2020-11-05 09:52:15]  INFO generating the "Makefile_20201105095215.mta" file...
[2020-11-05 09:52:15]  INFO done
[2020-11-05 09:52:15]  INFO executing the "make -f Makefile_20201105095215.mta p=cf mtar=yhdi_mdm_pso.mtar strict=true mode=" command...
[2020-11-05 09:52:15]  INFO validating the MTA project
[2020-11-05 09:52:15]  INFO validating the MTA project
[2020-11-05 09:52:15]  INFO building the "db" module...
[2020-11-05 09:52:15]  INFO executing the "npm install --production" command...
.......
> @sap/hana-client@2.4.202 install /home/vsts/work/1/s/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node checkbuild.js

FATAL ERROR: A fatal error occurred during install.
/home/vsts/work/1/s/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.13: wanted: {"node":"^6.9.1 || ^8.0.0 || ^10.0.0 || ^12.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.13
npm WARN deploy@ No description
.npm WARN deploy@ No repository field.
npm WARN deploy@ No license field.

```

**Comment by tal-sapan** [comment]
Hi,

This seems to be a problem with the `@sap/hana-client` or `@sap/hdi-deploy` npm package which define the supported node.js versions.
The mbt doesn't have any restrictions on versions of the build tools like node.js.

Best regards,
Tal

**Comment by yogananda-muthaiah** [comment]
Hi 

Any update ?? 
`
> @sap/hana-client@2.4.202 install C:\Temp\CALM\learn\bookshop-java\cloud-cap-samples-java\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client
> node checkbuild.js

FATAL ERROR: A fatal error occurred during install.
The specified procedure could not be found.
\\?\C:\Temp\CALM\learn\bookshop-java\cloud-cap-samples-java\node_modules\@sap\hdi-deploy\node_modules\@sap\hana-client\prebuilt\ntamd64-msvc2010\hana-client.node
npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.15: wanted: {"node":"^6.9.1 || ^8.0.0 || ^10.0.0 || ^12.0.0"} (current: {"node":"14.15.1","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15
npm WARN bookshop-java@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! @sap/hana-client@2.4.202 install: `node checkbuild.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the @sap/hana-client@2.4.202 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above`

**Comment by tal-sapan** [comment]
Hi @yogananda-muthaiah,

Please upgrade the version of the `@sap/hdi-deploy` package. It seems that version 4 supports nodejs 14.

**Comment by saharitushree** [comment]
Hi Team , 

I also get the same error and dont know how to solve it ...Even it i update the node module , and i do a MTA build, i again get the error in package.json created inside db.

[2021-03-30 07:25:50]  INFO the build results of the "pal2-service-srv" module will be packaged and saved in the "/home/user/projects/scm-sapcap-pal2-service/.scm-sapcap-pal2-service_mta_build_tmp/pal2-service-srv" folder
[2021-03-30 07:26:10]  INFO finished building the "pal2-service-srv" module
[2021-03-30 07:26:10]  INFO building the "pal2-service-db-deployer" module...
[2021-03-30 07:26:10]  INFO executing the "npm install --production" command...
............npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v14.15.4-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @sap/hana-client@2.4.202 install /home/user/projects/scm-sapcap-pal2-service/gen/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node checkbuild.js

.FATAL ERROR: A fatal error occurred during install.
/home/user/projects/scm-sapcap-pal2-service/gen/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
.npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.15: wanted: {"node":"^6.9.1 || ^8.0.0 || ^10.0.0 || ^12.0.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15
npm WARN deploy@ No description
npm WARN deploy@ No repository field.
npm WARN deploy@ No license field.

Thanks 
Ritushree

**Comment by tal-sapan** [comment]
Hi @saharitushree,

Please check which version is specified for the `@sap/hdi-deploy` dependency in your `package.json` file.
It should be at least 4.

From these messages in the log you attached it looks like you are using version 3.11.15:
```
npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.15: wanted: {"node":"^6.9.1 || ^8.0.0 || ^10.0.0 || ^12.0.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15
```

Best regards,
Tal
