### ISSUE TITLE
Support for incremental builds

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-mta-build-tool#801]
Hello MBT Team,

in the [Roadmap](https://sap.github.io/cloud-mta-build-tool/roadmap/) the support for incremental builds was mentioned to be available in Q3-4/2019. As it's now already Q4/2020 I would like to know if the feature was already delivered but the roadmap needs an update?

Best regards
Gregor

**Comment by katunin-ng** [comment]
Hi Gregor,

Yes, we delivered the feature: "Supports incremental builds; in other words, one module at a time.".  
You can now use "mbt module-build" command to build modules individually. Here https://sap.github.io/cloud-mta-build-tool/usage/#auxiliary-commands you can find more details on the command options.

Regards
Natalia

**Comment by gregorwolf** [comment]
Thank you @katunin-ng  for the quick response. So it would be great if the Roadmap page can be updated.

**Comment by katunin-ng** [comment]
Hi Gregor,

You are right. I will take care.

Regards
Natalia
