### ISSUE TITLE
mbt could not support 4-digit version number in mta.yaml

### ISSUE THREAD

**Issue by bo-yu-li** [SAP/cloud-mta-build-tool#806]
Seems mbt could not support 4-digit version number in mta.yaml.
But our project need to use 4-digit version number (i.e. 20.11.0.0) for release, is there any way to solved this problem?

  - MBT Version: 1.0.16
  - OS Version: MacOS
  - If possible, provide a link to the project.

Steps to Reproduce:

1.Any ui5 project which use mbt to generate .mtar build
2.Open mta.yaml and changed the version to 1.2.3.4
3.Execute mbt build, you will see the following error:

ERROR the "mta.yaml" file is not valid: 
line 3: the "20.11.0.0" value of the "root.version" property does not match the "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$" pattern

**Comment by tal-sapan** [comment]
Hi,

The version must be in the semantic version format, see the [documentation](https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/f2b5e04971914e638bc406f554386226.html).

The MTA deployer uses the version number to determine if the new mtar you are deploying is older or newer than the current version, this is why following the semantic version format is required.

Best regards,
Tal
