### ISSUE TITLE
Error Building MTA file inside Azure Devops Build Pipeline

### ISSUE THREAD

**Issue by rahulv03** [SAP/cloud-mta-build-tool#810]
Command: mbt build

Error: could not build the MTA project: could not execute the "make -f Makefile_20201215153420.mta p=cf mtar= strict=true mode=" command: exec: "make": executable file not found in %PATH%

Can someone help me

**Comment by rahulv03** [comment]
I am using Windows Azure Agent to build this and installed mbt using npm, and make using choco

npm install -g mbt

choco install make

node -v   --> 10.9.0

npm -v --> 6.2.0

I am not finding any similar problems on web


![image](https://user-images.githubusercontent.com/31666836/102278257-124bde80-3eef-11eb-8e1f-e9d5848ade04.png)

**Comment by tal-sapan** [comment]
Hi,

Please make sure you can run `make` in your build environment. It is required for running `mbt`.

Best regards,
Tal

**Comment by rahulv03** [comment]
Hello @tal-sapan  thanks for your response

I am trying to install gnu-make in my pipeline which is running on windows agent using chocolatey install azure task

https://marketplace.visualstudio.com/items?itemName=gep13.chocolatey-azuredevops 

I am not sure, but I can confirm that it's either not installed or not in the correct path, because I can't see it in path too

even make -v fails saying "'make' is not recognized as an internal or external command,"

can you help me in fixing this

![image](https://user-images.githubusercontent.com/31666836/102403384-cb6fee80-3fab-11eb-99f4-d75530e1b3f1.png)


![image](https://user-images.githubusercontent.com/31666836/102403475-ecd0da80-3fab-11eb-8f64-1430edb9a106.png)


![image](https://user-images.githubusercontent.com/31666836/102403514-f8bc9c80-3fab-11eb-9380-c06f8413c483.png)

**Comment by rahulv03** [comment]
resolving the issue

I resolved it by installing GNU Make 4.3 using chocolatey and adding the installing path to the bin

this fixed it

**Comment by ApoorvaMakani10** [comment]
Hi [rahulv03](https://github.com/rahulv03),

Please can you share on show you have created this pipeline as I a trying to create a same pipeline and facing similar challenges
