### ISSUE TITLE
mbt already reads non existing(?) version 1.0.18

### ISSUE THREAD

**Issue by pawinnek** [SAP/cloud-mta-build-tool#817]
Hi,

I have problems with running mbt, because link to download it not exist:
https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.18/cloud-mta-build-tool_1.0.18_Windows_amd64.tar.gz

I see the change in code made by @CloudMTABot but there is no download link of this version yet.

**Comment by michawai** [comment]
Hi,
This release doesn't exist.
Code will be reverted.
Sorry for the confusion.
