### ISSUE TITLE
Unnecessary node_modules Being Packaged

### ISSUE THREAD

**Issue by shubhangtiwari** [SAP/cloud-mta-build-tool#824]
On building the application using `mbt build` all the node_modules are being packaged along with the code. This is unnecessary since CF deployment anyways executes `npm install --production` during deployment.

Not packaging node_modules reduces the final `mtar` size to ~95% less

Please provide the following info:

  - MBT Version: `1.1.0`
  - OS Version: All

Steps to Reproduce:

1. Build the project using `mbt build`

**Comment by tal-sapan** [comment]
Hi,

If the `node_modules` folder is packaged with the application, CF will not run `npm install`.
If you require a different logic during the package you can use a [custom builder](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder) (e.g. so it doesn't run `npm install` during the build) or exclude certain folders (like `node_modules`) from being packaged with the [`ignore` property](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-module-build-artifacts-to-package-into-mta-archive).

Best regards,
Tal
