### ISSUE TITLE
Empty module path results in different outcomes

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-mta-build-tool#825]
Hi SAP + Community,
we struggled arround with an issue while a mbt build. The pipeline is set up on AzureDevOps Cloud and results in a timeout while the mbt build is running:
![ado_pipeline_issue](https://user-images.githubusercontent.com/9018930/107620122-81765280-6c54-11eb-927a-325208d3e20d.png)

The agent of the pipeline will timeout after 30minutes and tell us, that there is not enough space left to fulfill our request.

   - MBT Version: latest (1.1.0)
  - OS Version: ubuntu-20.04 image as pipeline VM on Azure DevOps Pool

`ID: cbi_backend
_schema-version: '2.1'
description: 'CBI-Backend'
version: 0.0.1
modules:
  - name: cbi_backend
    type: nodejs  
    path: .
    parameters:
      disk-quota: 512M
      memory: 256M            
    requires:
      - name: [...]`

We did run the same mta.yaml on our local machines and it was working.
After a long time of try & catch, we figgured out the 'path' section is working on the local machine, but not on the cloud VM. We tried using other folder identifiers, like '/', '\' or '.', also without the 'path' attribute, the mbt build did not succeed. 

We solved this by adding a new folder on the repository and adding the folder-name to the 'path' attribute of the mta.yaml. So we're not using the root fodler anymore. We're afraid if this is only happening on Azure DevOps but wanted to 
a) highlight this here, that the next one having this issue 
b) wanted you, SAP, to highlight this on the 'Tips' [section](https://sap.github.io/cloud-mta-build-tool/performance/) to warn the next ones either

Thank you and regards,
Cedric

**Comment by allaVolkov** [comment]
Fix for the issue released in the version 1.1.1
