### ISSUE TITLE
MBT build command error: could not execute the "mvn clean package" command: fork/exec ~/apache-maven-3.6.3/bin/mvn: not a directory

### ISSUE THREAD

**Issue by i301632** [SAP/cloud-mta-build-tool#827]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: 1.1.0
  - OS Version: 10.15.7
  - If possible, provide a link to the project.

Steps to Reproduce:

1. Installed MBT using "npm install -g mbt"
2.Install Maven version 3.6.3
3.Create Spring boot project in visual studio and run "MBT build" it gives an error stating that "**could not execute the "mvn clean package" command: fork/exec ~/apache-maven-3.6.3/bin/mvn: not a directory**"

**Comment by michawai** [comment]
The installation of maven is not related to mbt.
Make sure you installed maven successfully and verify from visual studio you can build maven projects.
