### ISSUE TITLE
mbt build error: could not execute the "make -f Makefile_20210305162355.mta p=cf mtar= strict=true mode=" command: exec: "make": executable file not found in %PATH%

### ISSUE THREAD

**Issue by atanumallik1** [SAP/cloud-mta-build-tool#830]
Dear Colleagues, 
I am trying to run an "mbt build" on a CAP project. 
I am getting the following error:

C:\Users\I072405\Documents\workspace-spring-tool-suite-4-4.9.0.RELEASE\tesSAPBA>mbt build
[2021-03-05 16:23:55]  INFO Cloud MTA Build Tool version 1.1.0
[2021-03-05 16:23:55]  INFO generating the "Makefile_20210305162355.mta" file...
[2021-03-05 16:23:55]  INFO done
[2021-03-05 16:23:55]  INFO executing the "make -f Makefile_20210305162355.mta p=cf mtar= strict=true mode=" command...
Error: could not build the MTA project: could not execute the "make -f Makefile_20210305162355.mta p=cf mtar= strict=true mode=" command: exec: "make": executable file not found in %PATH%
---------------------------------------------- 

Please provide the following info:

  - MBT Version: Cloud MTA Build Tool version 1.1.0
  - OS Version: Windows on My local machine 
  - Project Link: https://github.com/atanumallik1/CAP_BAsic 

Steps to Reproduce:

1. clone the project 
2. run mbt build

Could you please help me how to fix the error.

**Comment by allaVolkov** [comment]
Hello @atanumallik1,

Please see the following: https://sap.github.io/cloud-mta-build-tool/makefile/

Regards,
Alla
