### ISSUE TITLE
Deployed Docs is inconsistent

### ISSUE THREAD

**Issue by broxmen** [SAP/cloud-mta-build-tool#833]
The deployed docs mention `mvn clean install` for the global command whereas the actual docs on `master` reflect `mvn clean package` as the command.

Not sure if it's the other way around here.

**Comment by broxmen** [comment]
Docs on master : https://github.com/SAP/cloud-mta-build-tool/blob/master/docs/docs/whatsnew.md
Deployed docs : https://sap.github.io/cloud-mta-build-tool/whatsnew/

**Comment by tal-sapan** [comment]
Hi,

The correct command is `mvn clean package`. We will update the deployed documentation.
Thanks for letting us know.

Best regards,
Tal

**Comment by tal-sapan** [comment]
Hi,

We updated the docs. Thanks.
