### ISSUE TITLE
Parallel execution feature release status.

### ISSUE THREAD

**Issue by i076118** [SAP/cloud-mta-build-tool#844]
Hi,
I wanted to know that when the parallel execution feature will be released?
As per the roadmap it was supposed to be release in Q4 2020 but it is not marked as release.
https://sap.github.io/cloud-mta-build-tool/roadmap/#milestone-4-q4-2020
Can you please let me know that when it will be released?

Thanks & Regards,
Sunny Garg

**Comment by katunin-ng** [comment]
Hi Sunny,

You can trigger the parallel build by using the 'mode' and 'jobs' options, e.g. "mbt build -m=verbose -j=8"
See here the full description: https://sap.github.io/cloud-mta-build-tool/usage/#one-step-build.

Note: these options are BETA features meaning that when the parallel build is included as an official feature the options names/behavior may change. Currently, I cannot provide exact timelines for releasing the feature. 

Regards
Natalia
