### ISSUE TITLE
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15

### ISSUE THREAD

**Issue by saharitushree** [SAP/cloud-mta-build-tool#845]
Hi Team - 

I was bulding my cap application using MTA . It was all good . But from yesterday , I keep on getting the below error . 
I have updated the new version of @sap/hdi-deploy i.e 4, but after while build the , the package ,json created in gen folder gives an error and .mtar is not created.

npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15

> @sap/hana-client@2.4.202 install /home/user/projects/scm-sapcap-pal2-service/gen/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client
> node checkbuild.js

.FATAL ERROR: A fatal error occurred during install.
/home/user/projects/scm-sapcap-pal2-service/gen/db/node_modules/@sap/hdi-deploy/node_modules/@sap/hana-client/prebuilt/linuxx86_64-gcc48/hana-client.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi
.npm WARN notsup Unsupported engine for @sap/hdi-deploy@3.11.15: wanted: {"node":"^6.9.1 || ^8.0.0 || ^10.0.0 || ^12.0.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @sap/hdi-deploy@3.11.15
npm WARN deploy@ No description
npm WARN deploy@ No repository field.
npm WARN deploy@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @sap/hana-client@2.4.202 install: `node checkbuild.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @sap/hana-client@2.4.202 install script.

Could you please let us know how to solve it .

Thanks
Ritushree Saha

**Comment by tal-sapan** [comment]
Hi,

> the package ,json created in gen folder gives an error and .mtar is not created.

What is generating the package.json file in the gen folder? Could you attach a link to the project?

Best regards,
Tal

**Comment by mani-gitarea** [comment]
Hi ,

I am getting the exact same issue. The node version in the image is creating a problem for some of the @sap modules. The SAP npm modules needs the older node version which is 8 but in the latest node 12/14 is there.

Can I use the image which has node 8 or is there a way to fix this?

![err](https://user-images.githubusercontent.com/32050306/114921280-ae98da00-9e2a-11eb-881e-c887a5c3a062.jpeg)

**Comment by saharitushree** [comment]
Hi Mani , 

We solved it by installing the installing the hana-cli globally and executed the command hana-cli createModule which will create the package.json in the db folder  . After this the mta build was successfull.

Thanks
Ritushree 

> Hi ,
> 
> I am getting the exact same issue. The node version in the image is creating a problem for some of the @SAP modules. The SAP npm modules needs the older node version which is 8 but in the latest node 12/14 is there.
> 
> Can I use the image which has node 8 or is there a way to fix this?
> 
> ![err](https://user-images.githubusercontent.com/32050306/114921280-ae98da00-9e2a-11eb-881e-c887a5c3a062.jpeg)

**Comment by mani-gitarea** [comment]
Hi,

Thank you for the response. How does that work for an existing project? We are into on premise system and its HANA MTA DWF project. Where do I mention the hana-cli in my project.

Not sure how to handle this in our situation.

**Comment by tal-sapan** [comment]
Hi @mani-gitarea ,

Node 8 is no longer in maintenance, you should upgrade the version of the node module and use a supported version (e.g. Node 12 or Node 14).
From the screenshot it seems that your package.json defines a dependency to the package [`@sap/hdbext`](https://www.npmjs.com/package/@sap/hdbext). Please upgrade it to the latest version and try again.

You can see the maintenance status of Node versions here: https://nodejs.org/en/about/releases/

Best regards,
Tal
