### ISSUE TITLE
Using yarn instead of npm install

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/cloud-mta-build-tool#847]
Hi! 

Probably a stupid question - but is it possible somehow to configure this tool to use yarn instead of  npm install?

It can significantly improve our CI pipepline and save some execution time.

Actually this question can be even tranformed into something bigger:

Is it possible to redefine some standard tasks such as npm? 

![image](https://user-images.githubusercontent.com/6381507/113458396-659c5b00-9412-11eb-8a8e-7767a24522fd.png)

Thanks!

**Comment by tal-sapan** [comment]
Hi,

Yes, you can define a custom builder for any module. See the [documentation](https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder).

Best regards,
Tal
