### ISSUE TITLE
mbtci/dockerfile: mkdir: missing operand

### ISSUE THREAD

**Issue by diraschk** [SAP/cloud-mta-build-tool#851]
Building a image with this dockerfile caused this error: mkdir: missing operand
https://hub.docker.com/r/devxci/mbtci/dockerfile

Solution: Setting missing ENV
ENV NODE_HOME=/opt/nodejs;

**Comment by michawai** [comment]
Please refer to our latest release to find new [docker images ](https://github.com/SAP/cloud-mta-build-tool#the-cloud-mta-build-tool-images) as https://hub.docker.com/r/devxci/mbtci is deprecated.
