### ISSUE TITLE
the mbt build changing war to jar for analytic adapter

### ISSUE THREAD

**Issue by soyuztechnologies** [SAP/cloud-mta-build-tool#855]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: 1.1.1
  - OS Version: 
  - If possible, provide a link to the project. - Please refer video https://www.youtube.com/watch?v=b5he1l6Y-J8
    
Steps to Reproduce:

1. Download yeoman template 1 result found in 1ms
saphanaacademy-haa
 saphanaacademy
0.0.6
Yeoman Generator for SAP HANA Analytics Adapter aka HAA

2. Create a project using the template wizard in BAS
3. Add the war file of hana analytic adapter
4. Run mbt build
5. The war file auto converted to jar and build fails
6.ERROR could not package the "hanaadpapr-srv" module while getting the build artifact: could not find the "/home/user/projects/hanaadpapr/srv/target/*.war" path

Attached  is a video.

https://user-images.githubusercontent.com/71425689/115135045-01dd7900-a033-11eb-8fce-d66ccf80cc14.mp4

**Comment by katunin-ng** [comment]
Hi,

The build configuration that I see in your video instructs MBT to run a command: "mvn clean package" for building your module. I assume this is what removes the uploaded war file. 

If you do not want this default behavior you can configure a custom builder: https://sap.github.io/cloud-mta-build-tool/configuration/#configuring-the-custom-builder. If you just want to package the uploaded war file use the option without commands all (second example in the link). In addition, you need to configure the folder where MBT will look for the module's build result: "build-result: target" or just upload the war directly into the module's folder.

Regards
Natalia
