### ISSUE TITLE
Add a full field documentation to the docs

### ISSUE THREAD

**Issue by Trivernis** [SAP/cloud-mta-build-tool#871]
The [current docs](https://sap.github.io/cloud-mta-build-tool/) feature a chapter for configuration in the `mta.yml` files but it lacks a full documentation of all fields those configuration files provide. A table of all possible fields and example values would help a lot in creating build configurations without having to rely on error messages telling me that a field is not valid. I know there is a pdf that seems to explain some of the fields but I think such crucial information belongs to the actual documentation.

For context: I'm using the SAP WebIDE to configure and execute mta builds.

**Comment by katunin-ng** [comment]
Hi,
The Cloud MBT documentation provides all details on how the mta.yaml file can be used to configure the build process which the primary goal of the tool.
Other sources are available to learn about MTA features and tools supporting the concept. 
For example, [here](https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US/f1caa871360c40e7be7ce4264ab9c336.html) you can find information on supported properties and parameters of different modules and resources. 
Regards
Natalia
