### ISSUE TITLE
Deploy single app (or subset of apps) 

### ISSUE THREAD

**Issue by meakgoz2** [SAP/cloud-mta-build-tool#875]
Hi, 

It would be awesome if we could deploy a single app.  
Most of the time I only need to deploy one application, and the rest of the apps are not changed.  
For the non-changed apps, the time spent is wasted (especially when we have a react app which needs to be bundled etc. its a good amount of time wasted.)

For now, I maintain `manifest.yaml` files separately for each app, but double maintenance is causing problems most of the times.

**Comment by katunin-ng** [comment]
Hi,
The partial build and deployment are already possible.
Please have a look at the examples [here](https://github.com/SAP-samples/cf-mta-examples/tree/main/partial-build-deploy).
And here are the links to the relevant documentation: 

- [build module commands](https://sap.github.io/cloud-mta-build-tool/usage/#auxiliary-commands)

- [deploy commands](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/65ddb1b51a0642148c6b468a759a8a2e.html)

Regards
Natalia
