### ISSUE TITLE
Error during deployment using roles and permissions

### ISSUE THREAD

**Issue by P1ll3P4ll3** [SAP/cloud-mta-build-tool#880]
Hello,
we get an error trying to use permissions in our app. In mta.yaml file the role is defined first and after that the application/module itself. This works fine with the old/deprecated version of the MTA Archive Builder. I was searching the Internet and read through the User Guide but couldn´t find any information on that. We are deploying the app on SAP BTP Neo.

Please see below our mta.yaml file and the error during deployment with neo-web-sdk.
  - MBT Version: 1.2.1
  - OS Version: Windows Server 2016 x64
  - neo-web-sdk-3.129.5

```
ID: com.some.app
_schema-version: "2.1"
version: 1.0.1

parameters:
  title: "App"
  description: "An app"
  logo: "data:image/png;base64,xyz"

modules:
  # Roles
  - name: app-ui-roles
    type: com.sap.hcp.html5.role
    path: roles
    parameters:
      name: APP_USER
      groups:
        - Group_App_Users # default group
  
  # HTML5 Application
  - name: app-ui
    type: html5
    path: webapp
    parameters:
      version: "1.0.1-${timestamp}"
      display-name: "App"
      description: "Some description"
      permissions:
        - name: APP_USER_PERMISSION
          role: APP_USER
    build-parameters:
      builder: zip
      ignore: [""]
    requires:
      - name: app-ui-roles

```

```
2021-07-02T13:46:04.2036327Z Deployment operation with id 'iXXXXXX' started.
2021-07-02T13:46:07.2210225Z 13:46:07 Start deploying MTA archive 'app-ui.mtar'
2021-07-02T13:46:07.2211058Z 13:46:07 Start deploying module 'app-ui-roles', type 'com.sap.hcp.html5.role'
2021-07-02T13:46:07.2269542Z 13:46:07 Module 'app-ui-roles' deployed successfully
2021-07-02T13:46:07.2270154Z 13:46:07 Start deploying module 'app-ui', type 'com.sap.hcp.html5'
2021-07-02T13:46:12.2353823Z 13:46:12 Failed to deploy module 'app-ui'. 'Error while updating permission role assignments. Permission [APP_USER_PERMISSION] is not defined in the application descriptor'
2021-07-02T13:46:12.2356251Z 13:46:12 MTA archive 'app-ui.mtar' deployment finished
2021-07-02T13:46:12.2375897Z 
2021-07-02T13:46:12.2376180Z 
2021-07-02T13:46:12.2376605Z (!) ERROR: MTA deployment failed.
2021-07-02T13:46:12.2412484Z If you need help, provide the output of the command and attach the log directory [C:\BuildTools\neo-java-web-sdk-3.129.5\tools\log]
```

It says "Permission [APP_USER_PERMISSION] is not defined in the application descriptor'". How can that be handled?

Thanks and best regards.

**Comment by katunin-ng** [comment]
Hi,

The MTA deployment functionality is provided by another tool. Please report the issue [here](https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/issues) or via [SAP community](https://community.sap.com/) channel.

Regards
Natalia

**Comment by P1ll3P4ll3** [comment]
Hi Natalia,
we are still using the NEO environment and not CF. So do we have to post an incident for SAP BTP Neo?

How do you explain that the issue doesn´t occur with the older version of MTA by SAP? This still works perfectly.

Thanks and best regards,
Philippe

**Comment by katunin-ng** [comment]
@P1ll3P4ll3 If you have an issue with deployment to Neo environment, please open a customer ticket on component BC-NEO-DPL. The corresponding colleagues will investigate the issue. And if they come to conclusion that the issue is caused by incorrect MTA build by MBT, they will transfer the ticket to us.

Regards
Natalia

**Comment by P1ll3P4ll3** [comment]
@katunin-ng How are permissions handled generally? Is this information contained in the guides here of MBT?

**Comment by katunin-ng** [comment]
@P1ll3P4ll3 Platform-specific MTA modeling topics are not covered by the MTA Build tool. 
[Here](https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US/f1caa871360c40e7be7ce4264ab9c336.html) you can find what module and resource types are supported in Neo environment. 
Search for the word "role". In those sections, you can find references to documentation about permissions handling in Neo.
If they do not answer your questions, please post them in SAP community.

Regards
Natalia
