### ISSUE TITLE
Support for Mac M1

### ISSUE THREAD

**Issue by navinkrishnan** [SAP/cloud-mta-build-tool#887]
Hi Colleagues,

I'm not able to install `mbt` in Mac M1 (Apple silicon processor). is it supported ?

I get the following error, via npm

```
command sh -c binwrap-install
npm ERR! /Users/i332371/.nvm/versions/node/v16.6.1/lib/node_modules/mbt/node_modules/binwrap/install.js:18
npm ERR!     throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!     ^
npm ERR! 
npm ERR! Error: No binaries are available for your platform: darwin-arm64
```

Regards,
Navin

**Comment by michawai** [comment]
Hello @navinkrishnan 
M1 is already supported but for consuming it from internal SAP a fix was added.
Please consume latest release: https://github.com/SAP/cloud-mta-build-tool/releases/tag/v1.2.3
Regards,
Michal
