### ISSUE TITLE
cloud-mta-build-tool v1.2.3 not found

### ISSUE THREAD

**Issue by agwermann** [SAP/cloud-mta-build-tool#888]
It looks a new version of cloud-mta-build-tool_v1.2.3 was released today, however this version was not published to SAP Nexus. 

Can you please confirm if this can be addressed by CAP or what is the correct channel to raise this issue?

New release: https://github.com/SAP/cloud-mta-build-tool/releases/tag/v1.2.3

**Comment by michawai** [comment]
Hello @agwermann,
Upload to internal SAP nexust is independent process which can take time.
Meanwhile you can use a specific version (like '1.2.2') instead of 'latest'.
Regards
