### ISSUE TITLE
M2 HOME not set or empty

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-mta-build-tool#890]
As the Cloud MTA Build Tool (Beta) has this information

> NOTE: devxci/mbtci has been deprecated and will not be maintained any more. It will be available until 30/09/2021. Use the new images instead.

on the page https://hub.docker.com/r/devxci/mbtci

we started to use the image by creating an own image and adding our certs.
When using it an error occours.

![image](https://user-images.githubusercontent.com/10464878/129890607-bd5b70f6-9e8f-4cdc-834c-917cae369bac.png)

I could set the variable but this would solvve it only for me.

**Comment by T1mey** [comment]
AS Said out Image is FROM mbtci-alpine:1.2.3 and only adds our certs. So yours won't Work AS well

**Comment by michawai** [comment]
The mbtci-alpine image is a basic image which supplies only mbt. It doesn't supply Java/Node. So there's no need to expose M2_HOME.
The other images as explained in the link I attached supply also Java and Node and therefore set the relevant environment variables.

**Comment by T1mey** [comment]
OK. Oversaw them
