### ISSUE TITLE
Ideas / Suggestions / Questions

### ISSUE THREAD

**Issue by T1mey** [SAP/cloud-mta-build-tool#891]
Hello @all,

I want to share some remarks.

**Docker images**
The suppied docker images with JAVA and NodeJS are only visible as packages. It's quite hard to find. As well the documentation and the examples are only talking about the alpine image. Found it ... but it can be made clearer.

**Dockerfiles**
It's not really clear out of the file scructure as well as from documentation which dockerfiles applies to what images. It can be founf in the build file.

**java8 vs java11 images**
Could it be that those images not derive from the alpine image? I have some trouble installing our certs in the java8 image. Used the same commands as for java11 image but there is no update-ca-certificates installed. Think java8 image is based on centos... 
If this is the case this is not really consistant.

**image size**
The image size of the java11 (maybe as well the java 8) is quite huge. ~650 MB each. 

**benefit**
What is the benefit of the decision to not continue the proper working devxci/mbtci image?

**Comment by michawai** [comment]
Hello @T1mey ,

Your feedback is appreciated 👍 

**Docker images**
Currently our Dockerfiles are generated during build time and therefore available via packages. In the root folder of the project you can only find the Dockerfile templates. As you find in our documentation, there's an explanation how to pull only the alpine image and we're considering to add the same for our other images.

**Dockerfiles**
In the documentation [The Cloud MTA Build Tool Images](https://github.com/SAP/cloud-mta-build-tool/tree/master#the-cloud-mta-build-tool-images) > [How to build the image](https://github.com/SAP/cloud-mta-build-tool/tree/master#how-to-build-the-image), there's an explanation how to override the relevant Dockerfile template and how to build it. We will update the documentation to be more clear.

**java8 vs java11 images**
You are right! We are working on a fix for using same distribution.

**Image size**
The images which contains Java and Node are huge indeed. To use a lightweight image we provide the alpine docker image (https://hub.docker.com/r/devxci/mbtci-alpine) which only contains MBT. See our [The Cloud MTA Build Tool Images](https://github.com/SAP/cloud-mta-build-tool/tree/master#the-cloud-mta-build-tool-images) > Notes.

**Benefit**
The "proper" working  devxci/mbtci image was not proper as we're obligated to use sapmachine image and not openJdk directly. Besides, there were requirements to supply images with MBT for Java 8 and Node 14. So, we prepared a set of images for this combination. As suggested in documentation, the best is to use mbtci-alpine which is very lightweight and to add only the needed tools for your scenario.

**Comment by michawai** [comment]
Issues will be fixed in next release by following PR: https://github.com/SAP/cloud-mta-build-tool/pull/895

**Comment by michawai** [comment]
New release 1.2.4 is published.
