### ISSUE TITLE
info  mtaBuild - Error: could not build the MTA project: could not execute the "make -f Makefile_20210818135545.mta p=CF mtar=Helium.mtar strict=true mode= t=\"./\"" command: exec: "make": executable file not found in $PATH

### ISSUE THREAD

**Issue by I501307** [SAP/cloud-mta-build-tool#892]
Currently using the devxci/mbtci-alpine:latest dockerImage to execute mta build step. It appears that make tool isn't installed. Is this intentional ? 

  - MBT Version: INFO Cloud MTA Build Tool version 1.2.3

**Comment by michawai** [comment]
Issues will be fixed in next release by following PR: https://github.com/SAP/cloud-mta-build-tool/pull/895

**Comment by michawai** [comment]
New release 1.2.4 is published.
