### ISSUE TITLE
Trojan Infected dockerImage

### ISSUE THREAD

**Issue by I501307** [SAP/cloud-mta-build-tool#893]
Upon doing an antivirus scan (clamAV) on dockerImage **https://hub.docker.com/r/devxci/mbtci-java8-node12** with sha-digest : **7bf6e22396525c6f268061d31b6fdde96c87ecd4dd05516616b3e4f857b9adbc** 
we get following result : 
**devxci_mbtci-java8-node12.tar: Multios.Trojan.ElectroRAT-9823393-0 FOUND**. This state of art is expected ? or are you aware of infected images within your repositories ? 
Also protecode scan throws error as : 
**info  protecodeExecuteScan - no trusted certs found / using default transport / insecure skip set to true / : continuing with existing tls config** - This dockerImage also has certs problem (nothing to do with configuration issues on our side here!!!)

Please provide the following info:
  - MBT Version: Cloud MTA Build Tool version 1.2.3

**Comment by I501307** [comment]
mbt-java8-node12 version 1.2.2 also infected with trojan

**Comment by michawai** [comment]
New release 1.2.4 is published.
