### ISSUE TITLE
Java 11 Docker Image: Use fixed version of sapmachine

### ISSUE THREAD

**Issue by bmcdonn2** [SAP/cloud-mta-build-tool#900]
The Java11 docker image uses the `latest` tag of `sapmachine` which is currently pegged at [Java17](https://github.com/SAP/SapMachine-infrastructure/blob/532baee8c97aee7c85f7b16523aeba4268c0ed96/dockerfiles/official/17/Dockerfile#L16):

https://github.com/SAP/cloud-mta-build-tool/blob/f41959899a5818ecbb65a5345de37a2b619306b1/Dockerfile_mbtci_java11#L1

This means that code that is compatible with Java11 but not Java17 will not work in an image that implies support for Java11. 

There is an existing tag in `sapmachine` for Java11 support [here](https://hub.docker.com/layers/sapmachine/library/sapmachine/11/images/sha256-1eee5cce8d5265cd833de6d572ea62afe2285e7288bee0d37c2b41ef9d3ac3b8?context=explore). Given that the docker image itself is designed to support Java11, wouldn't it be good practice to fix the `sapmachine` version to Java 11 by using this tag rather than `latest` which could shift over time?

**Comment by rimasirich** [comment]
Hi,
This issue was fixed by this PR: https://github.com/SAP/cloud-mta-build-tool/pull/901/files
Regards,
Rima
