### ISSUE TITLE
mbt binary missing in version 1.2.5

### ISSUE THREAD

**Issue by htammen** [SAP/cloud-mta-build-tool#909]
After updating to newest version (1.2.5) the mbt binary ist missing.

Please provide the following info:

  - MBT Version: 1.2.5
  - OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. run `npm install -g mbt`
2. run `mbt --version` 
3. Error `.nvm/versions/node/v14.16.1/bin/mbt: Datei oder Verzeichnis nicht gefunden` appears

**Comment by lindenrty2** [comment]
I have same problem , it's crazy

**Comment by kimmodragon** [comment]
Same issue here.

**Comment by rimasirich** [comment]
Hello colleagues,
We are aware of this issue and currently working with very high priority to fix it.
Sorry for the inconvenience🙏
Regards,
Rima

**Comment by rimasirich** [comment]
Hello,
The issue should be resolved now in the latest release 1.2.7.
Regards,
Rima

**Comment by htammen** [comment]
can confirm that it's fixed with 1.2.7
Thank you
