### ISSUE TITLE
Error while trying to install mbt globally

### ISSUE THREAD

**Issue by BazhukovTima** [SAP/cloud-mta-build-tool#910]
**Description:**

Error while trying to install mbt globally

**Please provide the following info:**

  - MBT Version: latest
  - OS Version: Windows 10

**Steps to Reproduce:**

1. npm install -g mbt

**Output:**

`npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/user/.node_modules_global/lib/node_modules/mbt/bin/mbt
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/user/.node_modules_global/lib/node_modules/mbt/bin/mbt'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-11-01T08_45_35_039Z-debug.log`

**Comment by rimasirich** [comment]
Hello colleagues,
We are aware of this issue and currently working with very high priority to fix it.
Sorry for the inconvenience🙏
Regards,
Rima

**Comment by rimasirich** [comment]
Hello,
The issue should be resolved now in the latest release 1.2.7.
Regards,
Rima
