### ISSUE TITLE
Java 17 (LTS) support

### ISSUE THREAD

**Issue by wlsc** [SAP/cloud-mta-build-tool#926]
I wish that MTA build tool would support Java 17 (LTS) and provide all necessary images for it.

**Comment by wlsc** [comment]
Any updates on this?

**Comment by davidabap** [comment]
Hello, any update on this ?

**Comment by wlsc** [comment]
@bd82 any updates on support of Java 17 for Docker images?

**Comment by bd82** [comment]
The Docker images are no longer part of mbt releases.
See: https://github.com/SAP/cloud-mta-build-tool#the-cloud-mta-build-tool-images-deprecated
