### ISSUE TITLE
mbtci image with oracle java8

### ISSUE THREAD

**Issue by anujacob1987** [SAP/cloud-mta-build-tool#927]
Hi Colleagues,

Is it possible to provide an mbtci image with oracle java8 ?
In our project, with sapjvm (image: mbtci-java8-node14 and mbtci-java8-node12 ), we are getting error "mtaBuild - java.lang.OutOfMemoryError: GC overhead limit exceeded".

Regards,
Anu Jacob

**Comment by bd82** [comment]
The Docker images are no longer part of mbt releases.
See: https://github.com/SAP/cloud-mta-build-tool#the-cloud-mta-build-tool-images-deprecated
