### ISSUE TITLE
Support Node 16 (on Java 11 and Java 17)

### ISSUE THREAD

**Issue by PLsap** [SAP/cloud-mta-build-tool#939]
Hello all,

I'm using [mbtci-java11-node14](https://github.com/orgs/SAP/packages/container/package/mbtci-java11-node14) but I'm looking for an version on the latest LTS, here node16. 

Would you be able to provide such image timely?

Best regards,

Lionel.

**Comment by vobu** [comment]
+1 - Node.js 16 LTS is the default Node version on BTP already

**Comment by wlsc** [comment]
@PLsap @vobu I have similar request on Java 17 here https://github.com/SAP/cloud-mta-build-tool/issues/926 and it seems that maintainers are not active on this project.

**Comment by vobu** [comment]
hmmm - is this thing on? at least some statement on the overall status of things™? @ShimiT @allaVolkov @michawai @tal-sapan

**Comment by michawai** [comment]
@rimasirich can you assist?

**Comment by AvitalMargalitSAP** [comment]
Hi everyone,
My name is Avital and i'm a PO in BAS, responsible for this issue.
Thank you for your feedback, we are familiar with this request and we are going to handle it during Q2 2022.

Best regards,
Avital

**Comment by wlsc** [comment]
@AvitalMargalitSAP take please this contribution PR into consideration as well https://github.com/SAP/cloud-mta-build-tool/pull/941

**Comment by 4lexBaum** [comment]
Hi @AvitalMargalitSAP,

any updates here? Node.js 16 is LTS since January...

Best Alex

**Comment by bd82** [comment]
Docker images are now out for nodejs 16 & 18

- https://hub.docker.com/r/devxci/mbtci-java11-node16
- https://hub.docker.com/r/devxci/mbtci-java11-node18

**Comment by bd82** [comment]
I am new to MTA/MBT so maybe I am missing something...

But could someone (@PLsap @wlsc @vobu @4lexBaum) please clarify why these pre-built images are
even needed?

> A Multitarget application (MTA) is logically a single application comprised of multiple parts created with different technologies, which share the same lifecycle.

### Question
I assume the development teams of these `single applications` know how to setup their **local** development environment with the required tools (e.g Java / NodeJS / Maven / ...). Is it too much to expect these teams to also configure a matching docker image?

### Example
If I need a docker image with both nodejs / Java / Maven I would:

1. start with the [cimg/openjdk:17.0-node](https://hub.docker.com/r/cimg/openjdk) image by CircleCI, as this is very popular and highly maintained image an even includes maven.
2. pick the java version (17).
3. pick the `-node` variant to get nodejs LTS (16).
4. end up with this image tag: `cimg/openjdk:17.0-node`
5. setup my CI to use this image and add a few commands before starting the application build:
  - `sudo npm install -g mbt@1.2.16`
  - `sudo npm install -g grunt-cli@1.4.3`
  - add anything else that is need e.g: (@ui5-cli / custom auth settings for corporate systems / ...).

### Reasoning

- The matrix of possible combination of tooling versions keeps increasing:
   - Java Versions (there will be 4 live LTS versions by end of next year)
   - Node Versions (normally 3 live versions)
   - Go versions (2 concurrent live versions https://endoflife.date/go)
 
- Other tools (maven / @ui5-cli / grunt-cli) don't seem to multiple the matrix as there are
   usually not multiple live "LTS" versions, but would still mandate updating the images when new versions are released.

- The matrix and the `other tools` could expand as new requests are incoming, e.g: #927 

- some of the docker images seem to be very specific to SAP internal tooling use cases.
  - https://github.com/SAP/cloud-mta-build-tool/blob/master/Dockerfile_mbtci_java11#L18-L34
  - Is a public image the right place for these configurations?
  - Should these images focus on specific internal SAP flows to limit scope?

WDYT?

**Comment by wlsc** [comment]
@bd82 I do need Java 17 Docker images with all the software of mta build tool that it provides. Long story short: Java 17 (LTS) is not supported by MTA (yet) and this is a gap as we cannot move to Java 17 until it will be offered.

**Comment by bd82** [comment]
@wlsc I understand that you need a specific set of tools (including mbt) in a docker image, but I still don't understand why you are **blocked** for achieving this without "official" support by MBT?

- What is your scenario? 
- What is the exact set of tools that you need in the docker image?
- What is your build system?
- How are you setting up your **local** dev env with this set of tools?

**Comment by bd82** [comment]
The Docker images are no longer part of mbt releases.
See: https://github.com/SAP/cloud-mta-build-tool#the-cloud-mta-build-tool-images-deprecated
