### ISSUE TITLE
[Query] MTA extension only to update the resources

### ISSUE THREAD

**Issue by AshwinSYadgiri** [SAP/cloud-mta-build-tool#942]
Hi Colleagues,

It is regarding a query and not a bug.

Is it possible to use the MTA extensions to only update the existing resources? Like for example I want to create an MTA extension file to update the database parameter and nothing else? In this case do i need to still define the "modules" section and then "resources" section or directly I can define the "resources" section?

Regards, Ashwin

**Comment by katunin-ng** [comment]
Hi Ashwin,

You need to define only the section that you want to extend. 
BTW you can validate the result deployment descriptor without building the whole project.
Just run command 'mbt mtad-gen -e=<your extenson files>'.  See [here ](https://sap.github.io/cloud-mta-build-tool/usage/#auxiliary-commands) for more details.

Regards
Natalia
