### ISSUE TITLE
build fails with mtaBuild - option-error: invalid option 'mtar'

### ISSUE THREAD

**Issue by prateekdhiman27** [SAP/cloud-mta-build-tool#943]
Please provide the following info:

  - MBT Version: - 3.6
  - OS Version: - Linux / Jenkins Running in Jenkins docker container. 
  - If possible, provide a link to the project. https://github.com/SAP-samples/cloud-cf-helloworld-nodejs 

Steps to Reproduce:
Hello Team
I am trying to build a simple project from SAP Samples using Jenkins

1. Run the CI CD Pipeline
2. Build Fails with Error

info  mtaBuild - Executing mta build call: "mbt build --mtar com.sap.piper.node.hello.world.mtar --platform CF --source ./ --target /var/jenkins_home/workspace/cloud-cf-pipeline_main"
info  mtaBuild - running command: mbt build --mtar com.sap.piper.node.hello.world.mtar --platform CF --source ./ --target /var/jenkins_home/workspace/cloud-cf-pipeline_main
**info  mtaBuild - option-error: invalid option 'mtar'**
info  mtaBuild - fatal error: errorDetails{"category":"build","correlationId":"http://localhost:8080/job/cloud-cf-pipeline/job/main/13/","error":"running command 'mbt' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute mta build","result":"failure","stepName":"mtaBuild","time":"2022-03-23T17:29:59.281537903Z"}
fatal mtaBuild - failed to execute mta build - running command 'mbt' failed: cmd.Run() failed: exit status 1
info  mtaBuild - persisting reports to GCS is disabled, because gcsBucketId is empty
info  mtaBuild - Step telemetry data:{"StepStartTime":"2022-03-23 17:29:59.242765506 +0000 UTC","PipelineURLHash":"39429eb7f68e5ebc913f29092a3490ba8a6dcea8","BuildURLHash":"337ecae5e25066df10e2891239d7a886e9c326f7","StageName":"build","StepName":"mtaBuild","ErrorCode":"1","StepDuration":"39","ErrorCategory":"build","CorrelationID":"http://localhost:8080/job/cloud-cf-pipeline/job/main/13/","PiperCommitHash":"26bf3808fe9e9715a5a9984a1a945017db7acd77","ErrorDetail":{"category":"build","correlationId":"http://localhost:8080/job/cloud-cf-pipeline/job/main/13/","error":"running command 'mbt' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute mta build","result":"failure","stepName":"mtaBuild","time":"2022-03-23T17:29:59.281537903Z"}}

Also tried to build it via terminal but I Get the same error that --mtar is invalid parameter

**Comment by katunin-ng** [comment]
Hi,

Please use the format provided in [tool's guide examples](https://sap.github.io/cloud-mta-build-tool/usage/): mbt build -p**=**cf --mtar**=**TestProject.mtar.

Regards
Natalia

**Comment by prateekdhiman27** [comment]
Hello Natalia

Thanks for the prompt reply. How do I change this command during runtime?
It gets executed by the ./piper library.

**+ ./piper mtaBuild**
time="2022-03-24T13:16:56Z" level=info msg="{  [] 0xa38580}" library=SAP/jenkins-library
info  mtaBuild - Using stageName 'build' from env variable
info  mtaBuild - Project config: '.pipeline/config.yml'
info  mtaBuild - running command: npm config get registry
info  mtaBuild - "mta.yaml" file found in project sources
info  mtaBuild - No timestamp contained in "mta.yaml". File has not been modified.
info  mtaBuild - Executing mta build call: "mbt build --mtar com.sap.piper.node.hello.world.mtar --platform CF --source ./ --target /var/jenkins_home/workspace/cloud-cf-pipeline_main"
info  mtaBuild - running command: mbt build --mtar com.sap.piper.node.hello.world.mtar --platform CF --source ./ --target /var/jenkins_home/workspace/cloud-cf-pipeline_main
info  mtaBuild - option-error: invalid option 'mtar'
info  mtaBuild - fatal error: errorDetails{"category":"build","correlationId":"http://localhost:8080/job/cloud-cf-pipeline/job/main/15/","error":"running command 'mbt' failed: cmd.Run() failed: exit status 1","library":"SAP/jenkins-library","message":"failed to execute mta build","result":"failure","stepName":"mtaBuild","time":"2022-03-24T13:16:56.222476293Z"}

Here is my Config File details

general:
steps:
  mtaBuild:
    platform: 'CF'

**Comment by katunin-ng** [comment]
Hi,

Unfortunately, I cannot answer this question. You need to contact the team responsible for the ./piper library.

Regards
Natalia
