### ISSUE TITLE
Different java versions in Different modules

### ISSUE THREAD

**Issue by saurav28** [SAP/cloud-mta-build-tool#944]
Hi All,

This is a consultation request.

We have a MTA comprised of different modules ( in Java , Node and Go)

We have multiple modules in Golang.

Just wanted to know if its possible to different java modules in different java versions like ModuleA will be in Java 8 and Module B in Java 11.

Best Regards,
Saurav

**Comment by katunin-ng** [comment]
Hi,

For building the modules the MBT tool just triggers the build commands according to module types default configurations or explicitly specified in the mta.yaml file. For modules of type java, it triggers 'mvn clean package' by default. The execution of the command depends on tools (JAVA, maven, jdk) and their versions installed in the build environment. If you can build your modules in your build enviroment by triggering the commands manualy, e.g. from a CLI, you can also configure the MBT tools to use these commands for automatic build.

Regards
Natalia

**Comment by katunin-ng** [comment]
Hi Saurav,
It does not depend on MBT capabilities. If you can build your modules in your build environment by triggering the commands manually, e.g. from a CLI, you can also configure the MBT tools to use these commands for the automatic build.
Regards
Natalia
