### ISSUE TITLE
mbt Build Error

### ISSUE THREAD

**Issue by WaqasBashir86** [SAP/cloud-mta-build-tool#954]
I have tried many times but I am getting this error while building mta.yaml  application:

"[2022-04-28 23:53:04]  INFO executing the "make -f Makefile_20220428235304.mta p=cf mtar= strict=true mode=" command...

Error: could not build the MTA project: could not execute the "make -f Makefile_20220428235304.mta p=cf mtar= strict=true mode=" command: exec: "make": executable file not found in %PATH%"

I am trying to follow exactly as you are doing but no successs. kindly help

**Comment by katunin-ng** [comment]
Hi,

You should install GNU Make on your machine as described [here](https://sap.github.io/cloud-mta-build-tool/makefile/).
If you already installed the tool, please make sure that the PATH environment variable is updated with the path where the tool is installed.

Regards
Natalia
