### ISSUE TITLE
Publish linux arm64 binary for native use on Docker with m1 macbook

### ISSUE THREAD

**Issue by fwilhe** [SAP/cloud-mta-build-tool#955]
Trying to build a "native" Docker image on a new Macbook using Docker desktop fails because `mbt` is not published for linux on arm64.

```
#9 48.61 > mbt@1.2.3 install /node_modules/mbt
#9 48.61 > binwrap-install
#9 48.61
#9 48.75 /node_modules/binwrap/install.js:18
#9 48.75     throw new Error("No binaries are available for your platform: " + buildId);
#9 48.75     ^
#9 48.75
#9 48.75 Error: No binaries are available for your platform: linux-arm64
#9 48.75     at install (/node_modules/binwrap/install.js:18:11)
#9 48.75     at Object.install (/node_modules/binwrap/index.js:14:14)
#9 48.75     at Object.<anonymous> (/node_modules/binwrap/bin/binwrap-install:18:9)
#9 48.75     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#9 48.75     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#9 48.75     at Module.load (internal/modules/cjs/loader.js:950:32)
#9 48.75     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
#9 48.75     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
#9 48.75     at internal/main/run_main_module.js:17:47
```

I see that darwin arm64 is available so I would assume there is no general issue with building for arm and it should be trivial to also publish for linux arm64 (as cross compiling is simple with go).

Please publish that version of the binary. Thanks.

**Comment by fwilhe** [comment]
Hi @ShimiT, @bd82, any chance to get this resolved? I think this would be a low effort change (see my pr #956) with large impact for mac users.

Thanks.

**Comment by bd82** [comment]
Hello @fwilhe 

I can install and run mbt successfully on my M1 Mac or inside a docker image with Docker Desktop.
I guess it is use X86 emulation ?

Is this issue still relevant now that the pre-built docker images are no longer part of this repo?
Perhaps except as a performance optimization ?

**Comment by bd82** [comment]
Ah I see its not missing MacOS ARM support but rather Linux/ARM support

**Comment by bd82** [comment]
`part of?` 

Do you suspect anything else is missing?
Otherwise I can try to merge and trigger a release job

**Comment by fwilhe** [comment]
Especially I'm not familiar with publishing via binwrap, so not sure if I got everything that needs to be adapted there.

**Comment by bd82** [comment]
@fwilhe please try with new version 1.2.18

**Comment by fwilhe** [comment]
Hi @bd82 

I can confirm the issue is resolved.

Thanks for taking care 👍
