### ISSUE TITLE
CDS Build command not working in BAS.

### ISSUE THREAD

**Issue by Love2Explore** [SAP/cloud-mta-build-tool#972]
HI Team,

My "cds build" command is not working in BAS from yesterday . It is getting stuck after below lines .

![image](https://user-images.githubusercontent.com/22153611/172996731-c462922c-0570-4c6b-9c74-08cf53723deb.png)

Here are my package versions.

![image](https://user-images.githubusercontent.com/22153611/172996882-bb78cd55-9939-43b9-9587-308d50523126.png)

Best Regards,
Rewati Raman

**Comment by bd82** [comment]
I am not sure this is the right place to open this ticket.
Does this issue occur when using CDS directly? (meaning without MBT) ?
Does this issue occur outside of BAS? (local dev env).

Basically is this an MBT / CDS / BAS issue or some combination of these tools? 

Re-open if you believe it is an MBT issue.

**Comment by Love2Explore** [comment]
@bd82  Issue is solved , I deleted package-lock.json file and downloaded node module again.
Please close the Incident . 

In case of some question or Blocker related to CAP where can I post my question or query?
