### ISSUE TITLE
The version of maven in default image is low.

### ISSUE THREAD

**Issue by iamSmallY** [SAP/cloud-mta-build-tool#988]
* I used MBT in my project and I use the default setting of it by just setting `useCloudMbt: true`. It will pull the `devxci/mbtci-java11-node14` docker when building and the maven version in it is 3.3.9. 
* My project has a dependency named `maven-pmd-plugin` and it recently upgraded and not support the old version of maven. (https://issues.apache.org/jira/browse/MPMD-353). When I build it, there is an error
    > error mtaBuild - [ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.18.0:pmd (pmd) on project manualprocedure-srv: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.18.0:pmd failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-pmd-plugin:3.18.0:pmd: java.lang.NoSuchMethodError: 'org.fusesource.jansi.AnsiPrintStream org.fusesource.jansi.AnsiConsole.out()'
* So if there is a plan to upgrade the maven version in the default image or I have to use a certain image by setting the `mtaBuild` step? Which image should I use?

**Comment by young-yang03** [comment]
current, in devxci/mbtci-java11-node14 docker image, mvn version is 3.8.7
